// #import "PDFKit/PDFKit.js"
// #import "TestKit/TestKit.js"
/* global JSClass, TKTestSuite, PDFDeflateFilter */
/* global PDFNameObject, PDFObject, PDFDocumentObject, PDFPageTreeNodeObject, PDFPageObject, PDFResourcesObject, PDFGraphicsStateParametersObject, PDFStreamObject, PDFTrailerObject, PDFFontObject, PDFType1FontObject, PDFTrueTypeFontObject, PDFImageObject, PDFColorSpaceObject */
/* global TKAssert, TKAssertEquals, TKAssertNotEquals, TKAssertFloatEquals, TKAssertExactEquals, TKAssertNotExactEquals, TKAssertObjectEquals, TKAssertObjectNotEquals, TKAssertNotNull, TKAssertNull, TKAssertUndefined, TKAssertNotUndefined, TKAssertThrows, TKAssertLessThan, TKAssertLessThanOrEquals, TKAssertGreaterThan, TKAssertGreaterThanOrEquals */
'use strict';

JSClass("PDFDeflateFilterTests", TKTestSuite, {

    testDecode: function(){
        // First page of `TIFF 6.pdf` specification (PDF is drm encrypted; decrypted object 1039 0 using 18a30f1983febc0bd627 as rc4 key)
        var data = "eAF9kM9OxCAQxu99is+be+kCdmF79V9ivOwmJJ6xpVtW2rVA1viyPotAqwc1ZkiYDPPN/D4m7DGBxOCUQdQMTuMJI9Y3nqLxoDl8EzvS6/DdZ3NGYLPaFj26PItvS1FzJiAYKlGVFREb8A0tGbkSP6enxQRx+hTXpJQmmaC0aAZcS9ClOl9ywFrKRCQ7XMreeMSjELQP2N3e48NqHPSonQq6xfM7duqgfbkq5DEp2aK8WCEW7mTkjTZZsvkbgtc1ZoivxvQfxd/EfCuW5v+IH0LiNWPQYxv5wglnZU0bYRF6nRw8moCjOivfOPMa0Dk16LeTe5ktZJD9J9vPbN0=".dataByDecodingBase64();
        var filter = PDFDeflateFilter.init();
        var decoded = filter.decode(data);
        var expected = [
        'q Q q 0 0 612 792 re W n /Cs1 cs 1 1 1 sc 0 792 m 612 792 l 612 0 l 0 0 l',
        'h f Q q 68.79627 72 474.4075 651.2037 re W n /Cs1 cs 0 0 0 sc q 1 0 0 1 72 711',
        'cm BT 11 0 0 11 0 0 Tm /TT1 1 Tf (This is a test PDF \xdele generated by Pages.)',
        'Tj /TT2 1 Tf (!) Tj ET Q /Cs2 cs 0 sc q 1 0 0 1 72 699 cm BT ET Q /Cs1 cs',
        '0 0 0 sc q 1 0 0 1 72 687 cm BT 11 0 0 11 0 0 Tm /TT1 1 Tf (It is intended to validate the PDFKit javascript framework.)',
        'Tj ET Q Q'
        ].join('\n').latin1();
        TKAssertObjectEquals(decoded, expected);
    }
});