// #import "PDFKit/PDFKit.js"
// #import "TestKit/TestKit.js"
/* global JSClass, TKTestSuite, PDFReader, TKExpectation */
/* global PDFIndirectObject, PDFNameObject, PDFObject, PDFDocumentObject, PDFPageTreeNodeObject, PDFPageObject, PDFResourcesObject, PDFGraphicsStateParametersObject, PDFStreamObject, PDFTrailerObject, PDFFontObject, PDFType1FontObject, PDFTrueTypeFontObject, PDFImageObject */
/* global TKAssert, TKAssertEquals, TKAssertNotEquals, TKAssertFloatEquals, TKAssertExactEquals, TKAssertNotExactEquals, TKAssertObjectEquals, TKAssertObjectNotEquals, TKAssertNotNull, TKAssertNull, TKAssertUndefined, TKAssertNotUndefined, TKAssertThrows, TKAssertLessThan, TKAssertLessThanOrEquals, TKAssertGreaterThan, TKAssertGreaterThanOrEquals */
'use strict';

JSClass("PDFTextExtractionTests", TKTestSuite, {

    testBasic: function(){
        var expectation = TKExpectation.init();
        expectation.call(this.getResourceData, this, "test", "pdf", function(data){
            TKAssertNotNull(data);
            var reader = PDFReader.initWithData(data);
            expectation.call(reader.open, reader, function(status, document){
                TKAssertEquals(status, PDFReader.Status.open);
                TKAssertNotNull(document);
                var page = document.page(0);
                expectation.call(page.getText, page, function(text){
                    // FIXME: text extraction is a work in progress, expected string should eventually change to have line breaks.
                    // And what's the deal with that "!"?
                    TKAssertEquals(text, "This is a test PDF \xdele generated by Pages.!It is intended to validate the PDFKit javascript framework.");
                }, this);
            }, this);
        }, this);
        this.wait(expectation, 5);
    }

});