// #import PDFKit
// #import TestKit
'use strict';

JSClass("PDFTextExtractionTests", TKTestSuite, {

    testBasic: function(){
        var expectation = TKExpectation.init();
        expectation.call(this.getResourceData, this, "test", "pdf", function(data){
            TKAssertNotNull(data);
            var reader = PDFReader.initWithData(data);
            expectation.call(reader.open, reader, function(status, document){
                TKAssertEquals(status, PDFReader.Status.open);
                TKAssertNotNull(document);
                var page = document.page(0);
                expectation.call(page.getText, page, function(text){
                    TKAssertEquals(text, "This is a test PDF \ufb01le generated by Pages.\nIt is intended to validate the PDFKit javascript framework.");
                }, this);
            }, this);
        }, this);
        this.wait(expectation, 5);
    }

});