// Copyright 2020 Breakside Inc.
//
// Licensed under the Breakside Public License, Version 1.0 (the "License");
// you may not use this file except in compliance with the License.
// If a copy of the License was not distributed with this file, you may
// obtain a copy at
//
//     http://breakside.io/licenses/LICENSE-1.0.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// #import PDFKit
// #import TestKit
'use strict';

JSClass("PDFTextExtractionTests", TKTestSuite, {

    testBasic: function(){
        var expectation = TKExpectation.init();
        expectation.call(this.getResourceData, this, "test", "pdf", function(data){
            TKAssertNotNull(data);
            var reader = PDFReader.initWithData(data);
            expectation.call(reader.open, reader, function(status, document){
                TKAssertEquals(status, PDFReader.Status.open);
                TKAssertNotNull(document);
                var page = document.page(0);
                expectation.call(page.getText, page, function(text){
                    TKAssertEquals(text, "This is a test PDF \ufb01le generated by Pages.\nIt is intended to validate the PDFKit javascript framework.");
                }, this);
            }, this);
        }, this);
        this.wait(expectation, 5);
    }

});