copyright: Copyright © 2020 Breakside Inc.
introduced: 2020.28.0
kind: class
inherits: JSObject
summary: The default location to lookup secrets
description: |
  Given a secret name such as `databasePassword`(), this provider will
  essentially

  1. Call `getenv()`() on the exact name, `databasePassword`()
  2. If nothing is found, try `DATABASE_PASSWORD`()
topics:
  -
    name: Accessing Secrets
    members:
      -
        name: secretForName
        kind: method
        type: String
        nullable: true
        summary: Get the secret for the given name or a modified name
        arguments:
          -
            name: name
            type: String
            summary: The name of the secret to lookup
        description: |
          Given a secret name such as `databasePassword`(), this provider will
          essentially

          1. Call `getenv()`() on the exact name, `databasePassword`()
          2. If nothing is found, try `DATABASE_PASSWORD`()

          The exact name modification algorithm uppercases each letter and
          adds an underscore before any already-uppercased letter that is
          preceded by a lowercase letter.
