google:
  endpoint: https://accounts.google.com/
microsoft:
  endpoint: https://login.microsoftonline.com/common/v2.0/
apple:
  endpoint: https://appleid.apple.com/
facebook:
  endpoint: https://facebook.com/
authPrivacy:
  endpoint: https://authprivacy.com/