copyright: Copyright © 2020 Breakside Inc.
name: UIApplication Info
introduced: 2020.1.0
kind: dictionary
summary: A file of application properties
description: |
  The application's `Info` file is a YAML or JSON dictionary that contains
  properties instructing the `UIApplication` on how to initialize.

  The file should be named either `Info.yaml` or `Info.json` and placed at the
  root of the application's project.

  Among other things, the `Info` file
  - Indicates the application type
  - Uniquely identifies the application
  - Provides a application title
  - Lists the application version
  - Defines the acceptable `JSArguments` that can be passed to
    `applicationDidFinishLaunching()`
  - Declares the default font
  - Points to main spec file or application delgate class
  - Points to the application's icon

  Some of these values are used by the build system when packaging an
  application.  For example, the `JSBundleVersion` is used to tag the
  Docker image that is created for non-debug builds.
topics:
  -
    name: Identification
    members:
      -
        name: JSBundleType
        type: String
        summary: The type of project
        description: |
          Must be `html` for web based `UIApplication`s.
      -
        name: JSBundleIdentifier
        type: String
        summary: The globally unique identifier for the application
        description: |
          A bundle identifier should be globally unique, so the use of a
          reverse-domain syntax is strongly encouraged.

          For example, the identifier for this documentation viewer is
          ````
          io.breakside.JSKit.DocViewer
          ````
      -
        name: JSBundleVersion
        type: String
        summary: A series of dot-separated integers representing the
          applications current production version
        description: |
          The version number is used by the build system for such things as
          tagging the Docker image, so it's important to keep the number
          up to date when building production builds.

          While no exact convention is defined, we recommend using a
          Major.Minor.Bufix style version number.
  -
    name: Application Delegate
    members:
      -
        name: UIMainSpec
        type: String
        summary: The name of the spec that returns a `UIApplicationDelegate` as
          its `File's Owner`
        description: |
          The main spec typically defines a UI in addition to the application
          delegate, but is required to return via its `File's Owner` property
          an instance of a class that implements the `UIApplication` protocol.

          If you'd prefer not to use a spec file, you can specify the
          application delegate class via `UIApplicationDelegate`
        note: When providing a spec name, the `.spec.yaml` file extensions
          are implied and should not be included.
      -
        name: UIApplicationDelegate
        type: String
        summary: The name of a class that should be instantiated as the
          `UIApplication`'s `delegate`(UIApplication.delegate)
        description:
          An application is required to have a `delegate`(UIApplication.delegate)
          that implements the `UIApplicationDelegate`(UIApplication.UIApplicationDelegate)
          protocol.

          When specified as a class name here, the `UIApplication` will
          instantiate an object of that class to act as its delegate.

          You can alternatively supply a delegate by using `UIMainSpec`
  -
    name: Title and Icon
    members:
      -
        name: UIApplicationTitle
        type: String
        summary: A localizable string that will be displayed as the application's
          title
        description: |
          For a web based `UIApplication`, the title will be used as the HTML
          document's title.
      -
        name: UIApplicationIcon
        type: String
        summary: The name of an image resource to use as the application's icon
        description: |
          An icon image resouce is often an `.imageset` collection of `.png`
          images at `1x`, `2x`, and `3x` resolution.

          For web based `UIApplication`s, the builder will add the icon
          specified here as a favicon for the HTML page.
        note: When specifying an image resource, don't any any file extension
          like `.imageset` or `.png`.  The `JSBundle` resource system will
          find the best option from the file's basename alone.
  -
    name: Launch Options
    members:
      -
        name: UIApplicationLaunchOptions
        type: dictionary
        summary: The definitions of aguments that can be provided at launch
          time.
        description: |
          The value is a `dictionary` that matches what can be passed to
          `JSArguments.initWithOptions()`.

          Each key is a string representing an agument name, and each value
          is a `JSArguments.Option` dictionary.

          For web based applications, the launch options are extracted from
          the `fragment`(JSURL.fragment) of the page's URL.
  -
    name: Language Support
    members:
      -
        name: JSDevelopmentLanguage
        type: String
        summary: A language identifier that will be used as a final option
          if none of the user's preferred languages are supported by the app.
  -
    name: Fonts
    members:
      -
        name: UIApplicationSystemFont
        type: String
        summary: The name of a font resource to use as the default for UI
          elements
        description: |
          `UIKit` applications don't assume that any font is available without
          it being included in the application.

          Every application must include at least one font and specify here
          what the default font name is.

          Use the resource name corresponding to the font file, which is the
          font's filename excluding any extension.