// #import QRKit
// #import TestKit
// #import PDFKit
// #import SecurityKit
'use strict';

(function(){

JSClass("QRCodeTests", TKTestSuite, {

    testByteVersionDeterminationErrorLevelM: function(){
        var code = QRCode.initWithData(JSData.initWithLength(1));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithData(JSData.initWithLength(14));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithData(JSData.initWithLength(15));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithData(JSData.initWithLength(26));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithData(JSData.initWithLength(27));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithData(JSData.initWithLength(42));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithData(JSData.initWithLength(43));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithData(JSData.initWithLength(62));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithData(JSData.initWithLength(63));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithData(JSData.initWithLength(84));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithData(JSData.initWithLength(85));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithData(JSData.initWithLength(106));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithData(JSData.initWithLength(107));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithData(JSData.initWithLength(122));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithData(JSData.initWithLength(123));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithData(JSData.initWithLength(152));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithData(JSData.initWithLength(153));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithData(JSData.initWithLength(180));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithData(JSData.initWithLength(181));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithData(JSData.initWithLength(213));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithData(JSData.initWithLength(214));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithData(JSData.initWithLength(251));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithData(JSData.initWithLength(252));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithData(JSData.initWithLength(287));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithData(JSData.initWithLength(288));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithData(JSData.initWithLength(331));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithData(JSData.initWithLength(332));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithData(JSData.initWithLength(362));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithData(JSData.initWithLength(363));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithData(JSData.initWithLength(412));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithData(JSData.initWithLength(413));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithData(JSData.initWithLength(450));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithData(JSData.initWithLength(451));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithData(JSData.initWithLength(504));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithData(JSData.initWithLength(505));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithData(JSData.initWithLength(560));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithData(JSData.initWithLength(561));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithData(JSData.initWithLength(624));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithData(JSData.initWithLength(625));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithData(JSData.initWithLength(666));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithData(JSData.initWithLength(667));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithData(JSData.initWithLength(711));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithData(JSData.initWithLength(712));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithData(JSData.initWithLength(779));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithData(JSData.initWithLength(780));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithData(JSData.initWithLength(857));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithData(JSData.initWithLength(858));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithData(JSData.initWithLength(911));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithData(JSData.initWithLength(912));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithData(JSData.initWithLength(997));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithData(JSData.initWithLength(998));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithData(JSData.initWithLength(1059));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithData(JSData.initWithLength(1060));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithData(JSData.initWithLength(1125));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithData(JSData.initWithLength(1126));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithData(JSData.initWithLength(1190));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithData(JSData.initWithLength(1191));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithData(JSData.initWithLength(1264));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithData(JSData.initWithLength(1265));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithData(JSData.initWithLength(1370));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithData(JSData.initWithLength(1371));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithData(JSData.initWithLength(1452));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithData(JSData.initWithLength(1453));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithData(JSData.initWithLength(1538));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithData(JSData.initWithLength(1539));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithData(JSData.initWithLength(1628));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithData(JSData.initWithLength(1629));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithData(JSData.initWithLength(1722));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithData(JSData.initWithLength(1723));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithData(JSData.initWithLength(1809));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithData(JSData.initWithLength(1810));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithData(JSData.initWithLength(1911));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithData(JSData.initWithLength(1912));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithData(JSData.initWithLength(1989));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithData(JSData.initWithLength(1990));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithData(JSData.initWithLength(2099));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithData(JSData.initWithLength(2100));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithData(JSData.initWithLength(2213));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithData(JSData.initWithLength(2214));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithData(JSData.initWithLength(2331));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithData(JSData.initWithLength(2332));
        TKAssertNull(code);
        code = QRCode.initWithData(JSData.initWithLength(0));
        TKAssertNull(code);
    },

    testNumericVersionDeterminationErrorLevelM: function(){
        var code = QRCode.initWithString(numericString(1));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithString(numericString(34));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithString(numericString(35));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithString(numericString(63));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithString(numericString(64));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithString(numericString(101));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithString(numericString(102));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithString(numericString(149));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithString(numericString(150));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithString(numericString(202));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithString(numericString(203));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithString(numericString(255));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithString(numericString(256));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithString(numericString(293));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithString(numericString(294));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithString(numericString(365));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithString(numericString(366));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithString(numericString(432));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithString(numericString(433));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithString(numericString(513));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithString(numericString(514));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithString(numericString(604));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithString(numericString(605));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithString(numericString(691));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithString(numericString(692));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithString(numericString(796));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithString(numericString(797));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithString(numericString(871));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithString(numericString(872));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithString(numericString(991));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithString(numericString(992));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithString(numericString(1082));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithString(numericString(1083));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithString(numericString(1212));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithString(numericString(1213));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithString(numericString(1346));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithString(numericString(1347));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithString(numericString(1500));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithString(numericString(1501));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithString(numericString(1600));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithString(numericString(1601));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithString(numericString(1708));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithString(numericString(1709));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithString(numericString(1872));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithString(numericString(1873));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithString(numericString(2059));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithString(numericString(2060));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithString(numericString(2188));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithString(numericString(2189));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithString(numericString(2395));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithString(numericString(2396));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithString(numericString(2544));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithString(numericString(2545));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithString(numericString(2701));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithString(numericString(2702));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithString(numericString(2857));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithString(numericString(2858));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithString(numericString(3035));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithString(numericString(3036));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithString(numericString(3289));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithString(numericString(3290));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithString(numericString(3486));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithString(numericString(3487));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithString(numericString(3693));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithString(numericString(3694));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithString(numericString(3909));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithString(numericString(3910));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithString(numericString(4134));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithString(numericString(4135));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithString(numericString(4343));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithString(numericString(4344));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithString(numericString(4588));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithString(numericString(4589));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithString(numericString(4775));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithString(numericString(4776));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithString(numericString(5039));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithString(numericString(5040));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithString(numericString(5313));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithString(numericString(5314));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithString(numericString(5596));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithString(numericString(5597));
        TKAssertNull(code);
        code = QRCode.initWithString(numericString(0));
        TKAssertNull(code);
    },

    testAlphaumericVersionDeterminationErrorLevelM: function(){
        var code = QRCode.initWithString(alphanumericString(1));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithString(alphanumericString(20));
        TKAssertEquals(code.version, 1);
        code = QRCode.initWithString(alphanumericString(21));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithString(alphanumericString(38));
        TKAssertEquals(code.version, 2);
        code = QRCode.initWithString(alphanumericString(39));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithString(alphanumericString(61));
        TKAssertEquals(code.version, 3);
        code = QRCode.initWithString(alphanumericString(62));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithString(alphanumericString(90));
        TKAssertEquals(code.version, 4);
        code = QRCode.initWithString(alphanumericString(91));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithString(alphanumericString(122));
        TKAssertEquals(code.version, 5);
        code = QRCode.initWithString(alphanumericString(123));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithString(alphanumericString(154));
        TKAssertEquals(code.version, 6);
        code = QRCode.initWithString(alphanumericString(155));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithString(alphanumericString(178));
        TKAssertEquals(code.version, 7);
        code = QRCode.initWithString(alphanumericString(179));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithString(alphanumericString(221));
        TKAssertEquals(code.version, 8);
        code = QRCode.initWithString(alphanumericString(222));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithString(alphanumericString(262));
        TKAssertEquals(code.version, 9);
        code = QRCode.initWithString(alphanumericString(263));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithString(alphanumericString(311));
        TKAssertEquals(code.version, 10);
        code = QRCode.initWithString(alphanumericString(312));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithString(alphanumericString(366));
        TKAssertEquals(code.version, 11);
        code = QRCode.initWithString(alphanumericString(367));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithString(alphanumericString(419));
        TKAssertEquals(code.version, 12);
        code = QRCode.initWithString(alphanumericString(420));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithString(alphanumericString(483));
        TKAssertEquals(code.version, 13);
        code = QRCode.initWithString(alphanumericString(484));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithString(alphanumericString(528));
        TKAssertEquals(code.version, 14);
        code = QRCode.initWithString(alphanumericString(529));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithString(alphanumericString(600));
        TKAssertEquals(code.version, 15);
        code = QRCode.initWithString(alphanumericString(601));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithString(alphanumericString(656));
        TKAssertEquals(code.version, 16);
        code = QRCode.initWithString(alphanumericString(657));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithString(alphanumericString(734));
        TKAssertEquals(code.version, 17);
        code = QRCode.initWithString(alphanumericString(735));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithString(alphanumericString(816));
        TKAssertEquals(code.version, 18);
        code = QRCode.initWithString(alphanumericString(817));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithString(alphanumericString(909));
        TKAssertEquals(code.version, 19);
        code = QRCode.initWithString(alphanumericString(910));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithString(alphanumericString(970));
        TKAssertEquals(code.version, 20);
        code = QRCode.initWithString(alphanumericString(971));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithString(alphanumericString(1035));
        TKAssertEquals(code.version, 21);
        code = QRCode.initWithString(alphanumericString(1036));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithString(alphanumericString(1134));
        TKAssertEquals(code.version, 22);
        code = QRCode.initWithString(alphanumericString(1135));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithString(alphanumericString(1248));
        TKAssertEquals(code.version, 23);
        code = QRCode.initWithString(alphanumericString(1249));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithString(alphanumericString(1326));
        TKAssertEquals(code.version, 24);
        code = QRCode.initWithString(alphanumericString(1327));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithString(alphanumericString(1451));
        TKAssertEquals(code.version, 25);
        code = QRCode.initWithString(alphanumericString(1452));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithString(alphanumericString(1542));
        TKAssertEquals(code.version, 26);
        code = QRCode.initWithString(alphanumericString(1543));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithString(alphanumericString(1637));
        TKAssertEquals(code.version, 27);
        code = QRCode.initWithString(alphanumericString(1638));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithString(alphanumericString(1732));
        TKAssertEquals(code.version, 28);
        code = QRCode.initWithString(alphanumericString(1733));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithString(alphanumericString(1839));
        TKAssertEquals(code.version, 29);
        code = QRCode.initWithString(alphanumericString(1840));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithString(alphanumericString(1994));
        TKAssertEquals(code.version, 30);
        code = QRCode.initWithString(alphanumericString(1995));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithString(alphanumericString(2113));
        TKAssertEquals(code.version, 31);
        code = QRCode.initWithString(alphanumericString(2114));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithString(alphanumericString(2238));
        TKAssertEquals(code.version, 32);
        code = QRCode.initWithString(alphanumericString(2239));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithString(alphanumericString(2369));
        TKAssertEquals(code.version, 33);
        code = QRCode.initWithString(alphanumericString(2370));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithString(alphanumericString(2506));
        TKAssertEquals(code.version, 34);
        code = QRCode.initWithString(alphanumericString(2507));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithString(alphanumericString(2632));
        TKAssertEquals(code.version, 35);
        code = QRCode.initWithString(alphanumericString(2633));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithString(alphanumericString(2780));
        TKAssertEquals(code.version, 36);
        code = QRCode.initWithString(alphanumericString(2781));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithString(alphanumericString(2894));
        TKAssertEquals(code.version, 37);
        code = QRCode.initWithString(alphanumericString(2895));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithString(alphanumericString(3054));
        TKAssertEquals(code.version, 38);
        code = QRCode.initWithString(alphanumericString(3055));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithString(alphanumericString(3220));
        TKAssertEquals(code.version, 39);
        code = QRCode.initWithString(alphanumericString(3221));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithString(alphanumericString(3391));
        TKAssertEquals(code.version, 40);
        code = QRCode.initWithString(alphanumericString(3392));
        TKAssertNull(code);
        code = QRCode.initWithString(alphanumericString(0));
        TKAssertNull(code);
    },

    testBinaryDataCodewords :function(){
        var code = QRCode.initWithData(JSData.initWithArray([0x01, 0x02, 0x81, 0x82]));
        var codewords = code.dataCodewords();
        TKAssertEquals(codewords.length, 16);
        TKAssertEquals(codewords[0], 0x40);
        TKAssertEquals(codewords[1], 0x40);
        TKAssertEquals(codewords[2], 0x10);
        TKAssertEquals(codewords[3], 0x28);
        TKAssertEquals(codewords[4], 0x18);
        TKAssertEquals(codewords[5], 0x20);
        TKAssertEquals(codewords[6], 0xEC);
        TKAssertEquals(codewords[7], 0x11);
        TKAssertEquals(codewords[8], 0xEC);
        TKAssertEquals(codewords[9], 0x11);
        TKAssertEquals(codewords[10], 0xEC);
        TKAssertEquals(codewords[11], 0x11);
        TKAssertEquals(codewords[12], 0xEC);
        TKAssertEquals(codewords[13], 0x11);
        TKAssertEquals(codewords[14], 0xEC);
        TKAssertEquals(codewords[15], 0x11);
    },

    testNumericDataCodewords: function(){
        var code = QRCode.initWithString("01234567");
        var codewords = code.dataCodewords();
        TKAssertEquals(codewords.length, 16);
        TKAssertEquals(codewords[0], 0x10);
        TKAssertEquals(codewords[1], 0x20);
        TKAssertEquals(codewords[2], 0x0C);
        TKAssertEquals(codewords[3], 0x56);
        TKAssertEquals(codewords[4], 0x61);
        TKAssertEquals(codewords[5], 0x80);
        TKAssertEquals(codewords[6], 0xEC);
        TKAssertEquals(codewords[7], 0x11);
        TKAssertEquals(codewords[8], 0xEC);
        TKAssertEquals(codewords[9], 0x11);
        TKAssertEquals(codewords[10], 0xEC);
        TKAssertEquals(codewords[11], 0x11);
        TKAssertEquals(codewords[12], 0xEC);
        TKAssertEquals(codewords[13], 0x11);
        TKAssertEquals(codewords[14], 0xEC);
        TKAssertEquals(codewords[15], 0x11);
    },

    testAlphaumericDataCodewords: function(){
        var code = QRCode.initWithString("AC-42");
        var codewords = code.dataCodewords();
        TKAssertEquals(codewords.length, 16);
        TKAssertEquals(codewords[0], 0x20);
        TKAssertEquals(codewords[1], 0x29);
        TKAssertEquals(codewords[2], 0xCE);
        TKAssertEquals(codewords[3], 0xE7);
        TKAssertEquals(codewords[4], 0x21);
        TKAssertEquals(codewords[5], 0x00);
        TKAssertEquals(codewords[6], 0xEC);
        TKAssertEquals(codewords[7], 0x11);
        TKAssertEquals(codewords[8], 0xEC);
        TKAssertEquals(codewords[9], 0x11);
        TKAssertEquals(codewords[10], 0xEC);
        TKAssertEquals(codewords[11], 0x11);
        TKAssertEquals(codewords[12], 0xEC);
        TKAssertEquals(codewords[13], 0x11);
        TKAssertEquals(codewords[14], 0xEC);
        TKAssertEquals(codewords[15], 0x11);
    },

    // testPDF: async function(){
    //     var otp = SECOneTimePassword.init();
    //     // var url = JSURL.initWithString("https://jskit.dev");
    //     var url = otp.urlForUsername("Test", "Test App");
    //     var token = await otp.generateToken();
    //     console.log(token);
    //     token = await otp.generateTokenWithOffset(30);
    //     console.log(token);
    //     var code = QRCode.initWithURL(url);
    //     var pdfURL = JSFileManager.shared.urlForPath('/Users/oshaw/Desktop/qr.pdf');
    //     var context = PDFContext.initWithURL(pdfURL, JSRect(0,0,144,144));
    //     context.beginPage();
    //     context.drawQRCode(code, JSRect(0, 0, 144, 144));
    //     context.endPage();
    //     await context.endDocument();
    // }

});

var digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

var numericString = function(length){
    var s = "";
    for (var i = 0; i < length; ++i){
        s += digits[i % 10];
    }
    return s;
};

var characters = ["A", "1", "B", "2", "C", "3", "D", "4", "E", "5"];

var alphanumericString = function(length){
    var s = "";
    for (var i = 0; i < length; ++i){
        s += characters[i % 10];
    }
    return s;
};

})();