copyright: Copyright © 2020 Breakside Inc.
kind: document
name: Development Environment
summary: Available tools to help make JSKit development easier
description: |
  You can use your favorite Javascript development environment to write JSKit
  applications.

  Sublime Text
  ============
  We recommend [Sublime Text](https://www.sublimetext.com), and we've created an
  add-on package to help with JSKit-based app development.

  You can install it either:
  - With Package Control under the name `JSKit`(), or
  - From [github.com/breakside/sublime-jskit](https://github.com/breakside/sublime-jskit).

  To start with, we wanted to provide:
  - `JSKit` awareness when linting files
  - Snippets of common patterns
  - Auto-completions

  In order to lint your Javascript, we recommend also installing:
  - [SublimeLinter](http://www.sublimelinter.com) in SublimeText
  - [jshint](https://jshint.com) via `npm install --save-dev jshint` in your workspace
    folder

  Other Environments
  ==========
  [Let us know](https://jskit.dev/contact/) if there are other editors or IDEs
  that could use `JSKit` support.