// #import "PDFKit/PDFIndirectObject.js"
// #import "PDFKit/PDFName.js"
// #import "PDFKit/PDFObject.js"
// #import "PDFKit/PDFDocument.js"
// #import "PDFKit/PDFPages.js"
// #import "PDFKit/PDFPage.js"
// #import "PDFKit/PDFResources.js"
// #import "PDFKit/PDFGraphicsStateParameters.js"
// #import "PDFKit/PDFStream.js"
// #import "PDFKit/PDFTrailer.js"
// #import "PDFKit/PDFFont.js"
// #import "PDFKit/PDFFontDescriptor.js"
// #import "PDFKit/PDFCMap.js"
// #import "PDFKit/PDFXObject.js"
// #import "PDFKit/PDFImage.js"
// #import "PDFKit/PDFXrefStream.js"
// #import "PDFKit/PDFObjectStream.js"
// #import "PDFKit/PDFFunction.js"
/* global PDFIndirectObject, PDFName, PDFObject, PDFDocument, PDFPages, PDFPage, PDFResources, PDFGraphicsStateParameters, PDFStream, PDFTrailer, PDFFont, PDFType1Font, PDFType0Font, PDFTrueTypeFont, PDFMMType1Font, PDFType3Font, PDFCIDType0Font, PDFCIDType2Font, PDFFontDescriptor, PDFImage, PDFXrefStream, PDFObjectStream, PDFCMap, PDFFunctionSampled, PDFFunctionExponential, PDFFunctionStitching, PDFFunctionCalculator */
'use strict';