// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./APIKit" />

declare class APIMockRequest extends APIRequest{
  static initWithMethodAndURL<T>(this: { new(): T }, method: string, url: JSURL): T;
  initWithMethodAndURL(method: string, url: JSURL): this | void
  static initWithMethodAndURL<T>(this: { new(): T }, method: string, url: JSURL, object: any): T;
  initWithMethodAndURL(method: string, url: JSURL, object: any): this | void
  static initWithMethodAndURL<T>(this: { new(): T }, method: string, url: JSURL, form: JSFormFieldMap): T;
  initWithMethodAndURL(method: string, url: JSURL, form: JSFormFieldMap): this | void
  static initWithMethodAndURL<T>(this: { new(): T }, method: string, url: JSURL, data: JSData): T;
  initWithMethodAndURL(method: string, url: JSURL, data: JSData): this | void
  setData(data: JSData): void;
  setObject(object: any): void;
  setForm(form: JSFormFieldMap): void;
}
