// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class APIResponder extends JSObject{
  request: APIRequest;
  response: APIResponse;
  secrets: APISecrets;
  prepare(): Promise<undefined>;
  objectMethodForRequestMethod(requestMethod: string): (() => void);
  static initWithRequest<T>(this: { new(): T }, request: APIRequest): T;
  initWithRequest(request: APIRequest): this | void
}

declare class APIRequest extends JSObject{
  url: JSURL;
  method: string;
  headerMap: JSMIMEHeaderMap;
  origin: string | null;
  receivedAt: JSDate;
  contentType: JSMediaType;
  getValidObject(validatingContructionClass: JSClass, completion: (error: APIValidatingObject.Error | null, valid: JSObject) => void, target?: object): void;
  getValidObject(validatingContructionClass: JSClass): Promise<APIValidatingObject>;
  getValidForm(validatingContructionClass: JSClass, completion: (error: APIValidatingObject.Error | null, valid: JSObject) => void, target?: object): void;
  getValidForm(validatingContructionClass: JSClass): Promise<APIValidatingObject>;
  getValidatingObject(completion: (validator: APIValidatingObject) => void, target?: object): void;
  getValidatingObject(): Promise<APIValidatingObject>;
  getValidatingForm(completion: (validator: APIValidatingObject) => void, target?: object): void;
  getValidatingForm(): Promise<APIValidatingObject>;
  getObject(completion: (obj: object) => void, target?: object): void;
  getObject(): Promise<object>;
  getForm(completion: (form: JSFormFieldMap) => void, target?: object): void;
  getForm(): Promise<JSFormFieldMap>;
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
  getValidQuery(validatingContructionClass: JSClass): void;
  getValidatingQuery(): void;
  bearerToken: string | null;
  username: string | null;
  password: string | null;
  needsEntity(lastModified: JSDate, etag: string): void;
  accecptContentTypes: JSMediaType[];
}

declare class APIResponse extends JSObject{
  statusCode: APIResponse.StatusCode;
  headerMap: JSMIMEHeaderMap;
  data: JSData;
  object: {};
  contentType: JSMediaType;
  conentLength: number;
  etag: string;
  lastModified: JSDate;
}
declare namespace APIResponse{
  enum StatusCode{
    unknown,
    noResponse,
    continue,
    switchingProtocols,
    ok,
    created,
    accepted,
    nonAuthorativeInformation,
    noContent,
    resetContent,
    partialContent,
    multipleChoices,
    movedPermanently,
    found,
    seeOther,
    notModified,
    useProxy,
    temporaryRedirect,
    badRequest,
    unauthorized,
    paymentRequired,
    forbidden,
    notFound,
    methodNotAllowed,
    notAcceptable,
    proxyAuthenticationRequired,
    requestTimeout,
    conflict,
    gone,
    lengthRequired,
    preconditionFailed,
    payloadTooLarge,
    uriTooLong,
    unsupportedMediaType,
    rangeNotSatisfiable,
    expectationFailed,
    upgradeRequired,
    preconditionRequired,
    tooManyRequests,
    requestHeaderFieldsTooLarge,
    unavailableForLegalReasons,
    internalServerError,
    notImplemented,
    badGateway,
    serviceUnavailable,
    gatewayTimeout,
    httpVersionNotSupported,
  }
}

declare enum APIHeaders{
  contentType,
  contentLength,
  etag,
  lastModified,
}

declare class APIError{
  constructor(statusCode: APIResponse.StatusCode, message: string);
  statusCode: APIResponse.StatusCode;
  message: string;
}
declare function APIError(statusCode: APIResponse.StatusCode, message: string): APIError;


declare class APIValidatingObject extends JSObject{
  stringForKey(key: string): string;
  stringForKey(key: string, validator: (string: string) => void): string;
  stringForKey(key: string, defaultValue: string | null): string;
  stringForKey(key: string, defaultValue: string | null, validator: (string: string) => void): string;
  stringForKeyInLengthRange(key: string, min: number, max: number): string;
  stringForKeyInLengthRange(key: string, min: number, max: number, defaultValue: string | null): string;
  emailForKey(key: string): string;
  emailForKey(key: string, defaultValue: string | null): string;
  phoneForKey(key: string): string;
  phoneForKey(key: string, defaultValue: string | null): string;
  urlForKey(key: string): JSURL;
  urlForKey(key: string, defaultValue: string | null): string;
  numberForKey(key: string): number;
  numberForKey(key: string, validator: (number: number) => void): number;
  numberForKey(key: string, defaultValue: number | null): number;
  numberForKey(key: string, defaultValue: number | null, validator: (number: number) => void): number;
  numberForKeyInRange(key: string, min: number, max: number): number;
  numberForKeyInRange(key: string, min: number, max: number, defaultValue: number | null): number;
  integerForKey(key: string): number;
  integerForKey(key: string, defaultValue: number | null): number;
  integerForKeyInRange(key: string, min: number, max: number): number;
  integerForKeyInRange(key: string, min: number, max: number, defaultValue: number | null): number;
  booleanForKey(key: string): boolean;
  booleanForKey(key: string, defaultValue: boolean): boolean;
  objectForKey(key: string): APIValidatingObject;
  objectForKey(key: string, defaultValue: object): APIValidatingObject;
  validObjectForKey(validatingConstructionClass: JSClass, key: string): APIValidatingConstruction;
  validObjectForKey(validatingConstructionClass: JSClass, key: string, defaultValue: object): APIValidatingConstruction;
  arrayForKey(key: string): APIValidatingObject;
  arrayForKey(key: string, defaultValue: any[]): APIValidatingObject;
  optionForKey(key: string, optionSet: Set<any>): any;
  optionForKey(key: string, optionSet: Set<any>, defaultValue: any): any;
  base64DataForKey(key: string): JSData;
  base64DataForKey(key: string, defaultValue: boolean): JSData;
  base64URLDataForKey(key: string): JSData;
  base64URLDataForKey(key: string, defaultValue: boolean): JSData;
  length: number;
}
declare namespace APIValidatingObject{
  type ErrorInfo = {
    field: string;
    problem: string;
    expected: string | null;
    format: string | null;
    min: number | null;
    max: number | null;
    provided: number | null;
  };
  class Error{
    constructor(info: APIValidatingObject.ErrorInfo, message?: string);
    info: APIValidatingObject.ErrorInfo;
    message: string;
  }
  function Error(info: APIValidatingObject.ErrorInfo, message?: string): Error;
  
}

declare interface APIValidatingConstruction{
  initWithValidatingObject(validatingObject: APIValidatingObject): this | void
}

declare class APISecrets extends JSObject{
  static initWithNames<T>(this: { new(): T }, names: string[]): T;
  initWithNames(names: string[]): this | void
  valueForName(name: string): string | null;
  stringForName(name: string): string | null;
  urlForName(name: string): JSURL | null;
  urlForName(name: string, baseURL: JSURL): JSURL | null;
  integerForName(name: string): number | null;
  base64DataForName(name: string): JSData | null;
  base64URLDataForName(name: string): JSData | null;
  hex4DataForName(name: string): JSData | null;
  addProvider(provider: APISecretsProvider): void;
}

declare class APISecretsProvider extends JSObject{
  secretForName(name: string): string | null;
}

declare class APISecretsEnvironmentProvider extends JSObject{
  secretForName(name: string): string | null;
}
