// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./SecurityKit" />

declare class OAService extends JSObject{
  static google: OAService;
  static microsoft: OAService;
  static apple: OAService;
  static facebook: OAService;
  static initWithEndpointURL<T>(this: { new(): T }, endpointURL: JSURL): T;
  initWithEndpointURL(endpointURL: JSURL): this | void
  load(completion: (success: boolean) => void, target?: object): void;
  load(): Promise<void>;
  authenticationURL: JSURL;
  tokenURL: JSURL;
  keys(completion: (keys: SECJSONWebToken.JSONWebKey[]) => void, target?: object): void;
  keys(): Promise<SECJSONWebToken.JSONWebKey[]>;
}

declare class OASession extends JSObject{
  static initWithService<T>(this: { new(): T }, service: OAService, clientId: string): T;
  initWithService(service: OAService, clientId: string): this | void
  scopes: string[];
  loginHint: string | null;
  state: string;
  redirectURL: JSURL | null;
  responseTypes: string[];
  responseMode: string;
  authenticationURL: JSURL;
  exchangeCodeForToken(code: string, clientSecret: string, completion: (payload: {}) => void, target?: object): void;
  exchangeCodeForToken(code: string, clientSecret: string): Promise<{}>;
}
declare namespace OASession{
  enum ResponseMode{
    query,
    fragment,
  }
}
