// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class CHBarChart extends CHCategoryChart{
  barWidth: number;
  maskedCorners: CHSeriesBarStyle.Corners;
  cornerRadius: number;
}

declare class CHLineChart extends CHCategoryChart{
}

declare class CHStackedBarChart extends CHBarChart{
}

declare class CHAreaChart extends CHCategoryChart{
}

declare class CHStackedAreaChart extends CHAreaChart{
}

declare class CHPieChart extends CHChart{
  showNames: boolean;
  showValues: boolean;
  showValuesAsPercentages: boolean;
  labelPosition: number;
  labelFont: JSFont;
  labelTextColor: JSColor;
  labelTextAlignment: JSTextAlignment;
  labelShadowColor: JSColor | null;
  labelShadowOffset: JSPoint;
  labelShadowRadius: number;
  valueFormatter: JSNumberFormatter;
  legend: CHLegend;
  setDataPoints(values: number[], names: string[]): void;
  defaultSeriesStyle: CHSeriesStyle;
}

declare class CHCategoryChart extends CHChart{
  categoryAxis: CHCategoryAxis;
  valueAxis: CHValueAxis;
  valueDirection: CHAxis.Direction;
  legend: CHLegend;
  chartInsets: JSInsets;
  addValues(values: number[], name: string): void;
  defaultSeriesStyle: CHSeriesStyle;
  drawValuesInContext(context: JSContext, rect: JSRect): void;
}

declare class CHChart extends JSObject{
  static initWithTheme<T>(this: { new(): T }, theme: CHTheme): T;
  initWithTheme(theme: CHTheme): this | void
  series: CHSeries[];
  addSeries(series: CHSeries): void;
  drawInContext(context: JSContext, size: JSSize): void;
  colorForSeriesAtIndex(index: number): JSColor;
  numberOfNamesInLegend(): number;
  nameInLegendAtIndex(index: number): string;
  drawSymbolForNameInLegendAtIndex(legend: CHLegend, index: number, context: JSContext, rect: JSRect): void;
}

declare class CHSeries extends JSObject{
  static initWithName<T>(this: { new(): T }, name: string, style: CHSeriesStyle, values?: any[]): T;
  initWithName(name: string, style: CHSeriesStyle, values?: any[]): this | void
  name: string;
  values: any[];
  addValue(value: any): void;
  style: CHSeriesStyle;
}

declare class CHAxis extends JSObject{
  static initWithStyle<T>(this: { new(): T }, style: CHAxisStyle): T;
  initWithStyle(style: CHAxisStyle): this | void
  direction: CHAxis.Direction;
  edge: CHAxis.Edge;
  style: CHAxisStyle;
  getMajorPositions(p0: number, p1: number): number[];
  getMinorPositions(p0: number, p1: number): number[];
  getMajorLabels(): string[];
}
declare namespace CHAxis{
  enum Direction{
    horizontal,
    vertical,
  }
  enum Edge{
    leading,
    trailing,
  }
}

declare class CHCategoryAxis extends CHAxis{
  categories: string[];
}

declare class CHValueAxis extends CHAxis{
  minimumValue: number;
  maximumValue: number;
  numberOfMajorSteps: number;
  numberOfMinorSteps: number;
  valueFormatter: JSNumberFormatter;
}

declare class CHLegend extends JSObject{
  static initWithStyle<T>(this: { new(): T }, style: CHLegendStyle): T;
  initWithStyle(style: CHLegendStyle): this | void
  placement: CHLegend.Placement;
  chartSpacing: number;
  style: CHLegendStyle;
}
declare namespace CHLegend{
  enum Placement{
    none,
    above,
    below,
    left,
    right,
  }
}

declare class CHTheme extends JSObject{
  static initWithColors<T>(this: { new(): T }, colors: JSColor[]): T;
  initWithColors(colors: JSColor[]): this | void
  valueAxisStyle: CHAxisStyle;
  categoryAxisStyle: CHAxisStyle;
  legendStyle: CHLegendStyle;
  barStyle: CHSeriesBarStyle;
  lineStyle: CHSeriesLineStyle;
  areaStyle: CHSeriesAreaStyle;
  wedgeStyle: CHSeriesWedgeStyle;
}

declare class CHSeriesStyle extends JSObject{
  static initWithColor<T>(this: { new(): T }, color: JSColor): T;
  initWithColor(color: JSColor): this | void
  styleWithColor(color: JSColor): void;
  color: JSColor;
}

declare class CHSeriesBarStyle extends CHSeriesStyle{
  borderWidth: number;
  borderColor: JSColor;
  maskedBorders: CHSeriesBarStyle.Sides;
}
declare namespace CHSeriesBarStyle{
  enum Sides{
    none,
    all,
    leading,
    trailing,
    base,
    end,
  }
  enum Corners{
    none,
    all,
    baseLeading,
    baseTrailing,
    endLeading,
    endTrailing,
    base,
    end,
    leading,
    trailing,
  }
}

declare class CHSeriesLineStyle extends CHSeriesStyle{
  lineWidth: number;
  lineDashLengths: number[] | null;
  lineCap: JSContext.LineCap;
  lineJoin: JSContext.LineJoin;
  symbolPath: JSPath | null;
  symbolFillColor: JSColor | null;
  symbolStrokeColor: JSColor | null;
  symbolLineWidth: number;
}

declare class CHSeriesAreaStyle extends CHSeriesLineStyle{
  lineColor: JSColor | null;
}

declare class CHSeriesWedgeStyle extends CHSeriesStyle{
}

declare class CHAxisStyle extends JSObject{
  lineWidth: number;
  lineColor: JSColor;
  showsLabels: boolean;
  labelFont: JSFont;
  labelTextColor: JSColor;
  labelAngle: number;
  labelInsets: JSInsets;
  labelPosition: CHAxisStyle.LabelPosition;
  majorTickMarkStyle: CHAxisStyle.TickMarkStyle;
  majorTickMarkLength: number;
  majorTickMarkWidth: number;
  majorTickMarkColor: JSColor;
  minorTickMarkStyle: CHAxisStyle.TickMarkStyle;
  minorTickMarkLength: number;
  minorTickMarkWidth: number;
  minorTickMarkColor: JSColor;
  majorGridlineColor: JSColor;
  majorGridlineWidth: number;
  majorGridlineDashLengths: number[] | null;
  minorGridlineColor: JSColor;
  minorGridlineWidth: number;
  minorGridlineDashLengths: number[] | null;
}
declare namespace CHAxisStyle{
  enum LabelPosition{
    onTickMarks,
    betweenTickMarks,
  }
  enum TickMarkStyle{
    none,
    inside,
    outside,
    centered,
  }
}

declare class CHLegendStyle extends JSObject{
  font: JSFont;
  textColor: JSColor;
}

interface JSContext{
  drawChartInRect(chart: CHChart, rect: JSRect): void;
}
