// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./SecurityKit" />

declare class DBObjectDatabase extends JSObject{
  static initWithURL<T>(this: { new(): T }, url: JSURL): T;
  initWithURL(url: JSURL): this | void
  static initInMemory<T>(this: { new(): T }): T;
  initInMemory(): this | void
  static initWithObjectStore<T>(this: { new(): T }, store: DBObjectStore): T;
  initWithObjectStore(store: DBObjectStore): this | void
  open(completion: (success: boolean) => void, target?: object): void;
  close(completion: () => void, target?: object): void;
  open(): Promise<void>;
  close(): Promise<void>;
  object(id: string, completion: (object: DBStorable | null, error: Error | null) => void, target?: object): void;
  object(id: string): Promise<DBStorable>;
  objectOfClass(id: string, expectedClass: JSClass, completion: (object: DBStorable | null) => void, target?: object): void;
  objectOfClass(id: string, expectedClass: JSClass): Promise<DBStorable>;
  save(object: DBStorable, completion: (success: boolean) => void, target?: object): void;
  save(object: DBStorable): Promise<boolean>;
  saveExpiring(object: DBStorable, lifetimeInterval: JSTimeInterval, completion: (success: boolean) => void, target?: object): void;
  saveExpiring(object: DBStorable, lifetimeInterval: JSTimeInterval): Promise<boolean>;
  delete(id: string, completion: (success: boolean) => void, target?: object): void;
  delete(id: string): Promise<void>;
  encryptionDefaults: DBObjectDatabase.DBEncryptionOptions;
  keystore: SECKeystore;
  setKeystore(keystore: SECKeystore, defaultKeyIdentifier: string, keyBitLength: number): void;
  incrementExpiring(id: string, lifetimeInterval: JSTimeInterval, completion: (success: boolean) => void, target?: object): void;
  incrementExpiring(id: string, lifetimeInterval: JSTimeInterval): Promise<boolean>;
  registerStorableClass(storableClass: JSClass, prefix: string): void;
}
declare namespace DBObjectDatabase{
  type DBEncryptionOptions = {
    algorithm: SECCipher.Algorithm;
    keyIdentifier: string;
    keyBitLength: number;
  };
}

declare class DBObjectStore extends JSObject{
  open(completion: (success: boolean) => void): void;
  open(): Promise<void>;
  close(completion: () => void): void;
  close(): Promise<void>;
  object(id: string, completion: (object: {} | null, error: Error | null) => void): void;
  object(id: string): Promise<{}>;
  save(object: {}, completion: (success: boolean) => void): void;
  save(object: {}): Promise<boolean>;
  saveExpiring(object: {}, lifetimeInterval: JSTimeInterval, completion: (success: boolean) => void): void;
  saveExpiring(object: {}, lifetimeInterval: JSTimeInterval): Promise<boolean>;
  delete(id: string, completion: (success: boolean) => void, target?: object): void;
  delete(id: string): Promise<boolean>;
  incrementExpiring(id: string, lifetimeInterval: JSTimeInterval, completion: (success: boolean) => void, target?: object): void;
  incrementExpiring(id: string, lifetimeInterval: JSTimeInterval): Promise<boolean>;
}

declare interface DBStorable{
  id: string;
  initFromStorableDictionary(dictionary: {}): this | void
  encodeToStorableDictionary(dictionary: {}): {};
}

declare function DBID(prefix: string, ...hashable: (string | JSData)[]): string;

declare class DBEncryptedObject implements DBStorable{
  static initWithObject<T>(this: { new(): T }, object: DBStorable): T;
  initWithObject(object: DBStorable): this | void
  object: DBStorable | null;
  decrypt(completion: (success: boolean) => void, target?: object): void;
  decrypt(): Promise<void>;
  id: string;
  static initFromStorableDictionary<T>(this: { new(): T }, dictionary: {}): T;
  initFromStorableDictionary(dictionary: {}): this | void
  encodeToStorableDictionary(dictionary: {}): {};
}

declare class DBObjectGraph extends JSObjectGraph{
  static initWithObjectDatabase<T>(this: { new(): T }, database: DBObjectDatabase): T;
  initWithObjectDatabase(database: DBObjectDatabase): this | void
  addObjectDatabase(database: DBObjectDatabase): void;
  objectOfClass(id: string, expectedClass: JSClass, completion: (object: DBStorable | null) => void, target?: object): void;
  objectOfClass(id: string, expectedClass: JSClass): Promise<DBStorable>;
}
