// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class JSDispatchQueue extends JSObject{
  static background: JSDispatchQueue;
  static init<T>(this: { new(): T }): T;
  init(): this | void
  enqueue(jobClass: JSClass, args: any[], completion: (error: Error | null, ...args: any[]) => void, target?: object): void;
  enqueue(jobClass: JSClass, args: any[]): Promise<any>;
  destroy(): void;
}

declare class JSDispatchJob extends JSObject{
  static initWithArguments<T>(this: { new(): T }, args: any[]): T;
  initWithArguments(args: any[]): this | void
  args: any[];
  run(completion: (...args: any[]) => void): void;
}
