// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class FNTOpenTypeFont extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData): T;
  initWithData(data: JSData): this | void
  widthOfGlyph(glyphIndex: number): number;
  glyphForCharacter(character: UnicodeChar): number;
  getCorrectedFont(completion: (font: JSFont) => void, target?: object): void;
  getCorrectedFont(): Promise<JSFont>;
  head: FNTOpenTypeFontTableHead;
  post: FNTOpenTypeFontTablePost;
  name: FNTOpenTypeFontTableName;
  hhea: FNTOpenTypeFontTableHhea;
  hmtx: FNTOpenTypeFontTableHmtx;
  cmap: FNTOpenTypeFontTableCmap;
}

declare class FNTOpenTypeFontTable extends JSObject{
  data: JSData;
  dataView: DataView;
}

declare class FNTOpenTypeFontTableHead extends FNTOpenTypeFontTable{
  majorVersion: number;
  minorVersion: number;
  majorRevision: number;
  minorRevision: number;
  checksumAdjustment: number;
  magicNumber: number;
  flags: number;
  createdHigh: number;
  createdLow: number;
  modifiedHigh: number;
  modifiedLow: number;
  macStyle: number;
  fontDirectionHint: number;
  unitsPerEM: number;
  xMin: number;
  yMin: number;
  xMax: number;
  yMax: number;
  lowestRecPPEM: number;
  indexToLocFormat: number;
  glyphDataFormat: number;
}

declare class FNTOpenTypeFontTableOS2 extends FNTOpenTypeFontTable{
  version: number;
  fsType: number;
  sFamilyClass: number;
  achVendID: number;
  fsSelection: number;
  sTypoAscender: number;
  sTypoDescender: number;
  sTypoLineGap: number;
  sxHeight: number;
  sCapHeight: number;
  xAvgCharWidth: number;
  usWinAscent: number;
  usWinDescent: number;
  usWeightClass: number;
  usWidthClass: number;
  usDefaultChar: number;
  usBreakChar: number;
  usMaxContext: number;
  usLowerOpticalPointSize: number;
  usUpperOpticalPointSize: number;
  ySubscriptXSize: number;
  ySubscriptYSize: number;
  ySubscriptXOffset: number;
  ySubscriptYOffset: number;
  ySuperscriptXSize: number;
  ySuperscriptYSize: number;
  ySuperscriptXOffset: number;
  ySuperscriptYOffset: number;
  yStrikeoutSize: number;
  yStrikeoutPosition: number;
  panose0: number;
  panose1: number;
  panose2: number;
  panose3: number;
  panose4: number;
  panose5: number;
  panose6: number;
  panose7: number;
  panose8: number;
  panose9: number;
  ulUnicodeRange1: number;
  ulUnicodeRange2: number;
  ulUnicodeRange3: number;
  ulUnicodeRange4: number;
  usFirstCharIndex: number;
  usLastCharIndex: number;
  ulCodePageRange1: number;
  ulCodePageRange2: number;
}

declare class FNTOpenTypeFontTablePost extends FNTOpenTypeFontTable{
  majorVersion: number;
  minorVersion: number;
  italicAngleWhole: number;
  italicAngleFraction: number;
  underlinePosition: number;
  underlineThickness: number;
  isFixedPitch: number;
  minMemType42: number;
  maxMemType42: number;
  minMemType1: number;
  maxMemType1: number;
}

declare class FNTOpenTypeFontTableName extends FNTOpenTypeFontTable{
  format: number;
  count: number;
  stringsOffset: number;
  family: string;
  face: string;
  uniqueID: string;
  postscript: string;
  fullName: string;
  getName(preferences: () => void): string;
  addName(platformId: number, encodingId: number, languageId: number, nameId: number, nameData: JSData): void;
}

declare class FNTOpenTypeFontTableHhea extends FNTOpenTypeFontTable{
  majorVersion: number;
  minorVersion: number;
  ascender: number;
  descender: number;
  lineGap: number;
  advanceWidthMax: number;
  minLeftSideBearing: number;
  minRightSideBearing: number;
  xMaxExtent: number;
  caretSlopeRise: number;
  caretSlopeRun: number;
  caretOffset: number;
  metricDataFormat: number;
  numberOfHMetrics: number;
}

declare class FNTOpenTypeFontTableHmtx extends FNTOpenTypeFontTable{
  widthOfGlyph(glyph: number): number;
  setWidths(widths: number[]): void;
}

declare class FNTOpenTypeFontTableCmap extends FNTOpenTypeFontTable{
  version: number;
  count: number;
  getMap(preferences: () => void): FNTOpenTypeFontCmap | null;
  addMap(platformId: number, specificId: number, map: FNTOpenTypeFontCmap): void;
}

declare class FNTOpenTypeFontCmap extends JSObject{
}

declare class FNTOpenTypeConstructor extends JSObject{
  static initWithTables<T>(this: { new(): T }, tables: FNTOpenTypeFontTable[]): T;
  initWithTables(tables: FNTOpenTypeFontTable[]): this | void
  static initWithGlyphType<T>(this: { new(): T }, glyphType: FNTOpenTypeConstructor.GlyphType): T;
  initWithGlyphType(glyphType: FNTOpenTypeConstructor.GlyphType): this | void
  addTable(table: FNTOpenTypeFontTable): void;
  setLineHeight(ascender: number, descender: number): void;
  setItalicAngle(angle: number): void;
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
}
declare namespace FNTOpenTypeConstructor{
  enum GlyphType{
    trueType,
    compactFontFormat,
  }
}

declare class FNTFontDescriptor extends JSFontDescriptor{
  static initWithOpenTypeData<T>(this: { new(): T }, data: JSData): T;
  initWithOpenTypeData(data: JSData): this | void
  static initWithOpenTypeFont<T>(this: { new(): T }, font: FNTOpenTypeFont): T;
  initWithOpenTypeFont(font: FNTOpenTypeFont): this | void
}

declare class FNTCompactFontFormat extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData): T | null;
  initWithData(data: JSData): this | void | null
  getOpenTypeData(externalInfo: FNTCompactFontFormat.ExternalInfo, completion: (data: JSData) => void, target?: object): void;
  getOpenTypeData(externalInfo: FNTCompactFontFormat.ExternalInfo): Promise<JSData>;
}
declare namespace FNTCompactFontFormat{
  type ExternalInfo = {
    bbox?: number[] | null;
    ascender?: number | null;
    descender?: number | null;
    singleByteEncoding?: number[] | null;
    diffs?: any[] | null;
    widths?: number[] | null;
    firstWidth?: number | null;
    lastWidth?: number | null;
    nominalWidth?: number | null;
  };
}

declare enum FNTAdobeNamesToUnicode{
  A,
  AE,
  AEsmall,
  Aacute,
  Aacutesmall,
  Acircumflex,
  Acircumflexsmall,
  Acutesmall,
  Adieresis,
  Adieresissmall,
  Agrave,
  Agravesmall,
  Alpha,
  Aring,
  Aringsmall,
  Asmall,
  Atilde,
  Atildesmall,
  B,
  Beta,
  Brevesmall,
  Bsmall,
  C,
  Caronsmall,
  Ccedilla,
  Ccedillasmall,
  Cedillasmall,
  Chi,
  Circumflexsmall,
  Csmall,
  D,
  Delta,
  Dieresissmall,
  Dotaccentsmall,
  Dsmall,
  E,
  Eacute,
  Eacutesmall,
  Ecircumflex,
  Ecircumflexsmall,
  Edieresis,
  Edieresissmall,
  Egrave,
  Egravesmall,
  Epsilon,
  Esmall,
  Eta,
  Eth,
  Ethsmall,
  Euro,
  F,
  Fsmall,
  G,
  Gamma,
  Gravesmall,
  Gsmall,
  H,
  Hsmall,
  Hungarumlautsmall,
  I,
  Iacute,
  Iacutesmall,
  Icircumflex,
  Icircumflexsmall,
  Idieresis,
  Idieresissmall,
  Ifraktur,
  Igrave,
  Igravesmall,
  Iota,
  Ismall,
  J,
  Jsmall,
  K,
  Kappa,
  Ksmall,
  L,
  Lambda,
  Lslash,
  Lslashsmall,
  Lsmall,
  M,
  Macronsmall,
  Msmall,
  Mu,
  N,
  Nsmall,
  Ntilde,
  Ntildesmall,
  Nu,
  O,
  OE,
  OEsmall,
  Oacute,
  Oacutesmall,
  Ocircumflex,
  Ocircumflexsmall,
  Odieresis,
  Odieresissmall,
  Ogoneksmall,
  Ograve,
  Ogravesmall,
  Omega,
  Omicron,
  Oslash,
  Oslashsmall,
  Osmall,
  Otilde,
  Otildesmall,
  P,
  Phi,
  Pi,
  Psi,
  Psmall,
  Q,
  Qsmall,
  R,
  Rfraktur,
  Rho,
  Ringsmall,
  Rsmall,
  S,
  Scaron,
  Scaronsmall,
  Sigma,
  Ssmall,
  T,
  Tau,
  Theta,
  Thorn,
  Thornsmall,
  Tildesmall,
  Tsmall,
  U,
  Uacute,
  Uacutesmall,
  Ucircumflex,
  Ucircumflexsmall,
  Udieresis,
  Udieresissmall,
  Ugrave,
  Ugravesmall,
  Upsilon,
  Upsilon1,
  Usmall,
  V,
  Vsmall,
  W,
  Wsmall,
  X,
  Xi,
  Xsmall,
  Y,
  Yacute,
  Yacutesmall,
  Ydieresis,
  Ydieresissmall,
  Ysmall,
  Z,
  Zcaron,
  Zcaronsmall,
  Zeta,
  Zsmall,
  a,
  aacute,
  acircumflex,
  acute,
  adieresis,
  ae,
  agrave,
  aleph,
  alpha,
  ampersand,
  ampersandsmall,
  angle,
  angleleft,
  angleright,
  approxequal,
  aring,
  arrowboth,
  arrowdblboth,
  arrowdbldown,
  arrowdblleft,
  arrowdblright,
  arrowdblup,
  arrowdown,
  arrowhorizex,
  arrowleft,
  arrowright,
  arrowup,
  arrowvertex,
  asciicircum,
  asciitilde,
  asterisk,
  asteriskmath,
  asuperior,
  at,
  atilde,
  b,
  backslash,
  bar,
  beta,
  braceex,
  braceleft,
  braceleftbt,
  braceleftmid,
  bracelefttp,
  braceright,
  bracerightbt,
  bracerightmid,
  bracerighttp,
  bracketleft,
  bracketleftbt,
  bracketleftex,
  bracketlefttp,
  bracketright,
  bracketrightbt,
  bracketrightex,
  bracketrighttp,
  breve,
  brokenbar,
  bsuperior,
  bullet,
  c,
  caron,
  carriagereturn,
  ccedilla,
  cedilla,
  cent,
  centinferior,
  centoldstyle,
  centsuperior,
  chi,
  circlemultiply,
  circleplus,
  circumflex,
  club,
  colon,
  colonmonetary,
  comma,
  commainferior,
  commasuperior,
  congruent,
  copyright,
  copyrightsans,
  copyrightserif,
  currency,
  d,
  dagger,
  daggerdbl,
  degree,
  delta,
  diamond,
  dieresis,
  divide,
  dollar,
  dollarinferior,
  dollaroldstyle,
  dollarsuperior,
  dotaccent,
  dotlessi,
  dotmath,
  dsuperior,
  e,
  eacute,
  ecircumflex,
  edieresis,
  egrave,
  eight,
  eightinferior,
  eightoldstyle,
  eightsuperior,
  element,
  ellipsis,
  emdash,
  emptyset,
  endash,
  epsilon,
  equal,
  equivalence,
  esuperior,
  eta,
  eth,
  exclam,
  exclamdown,
  exclamdownsmall,
  exclamsmall,
  existential,
  f,
  ff,
  ffi,
  ffl,
  fi,
  f_i,
  figuredash,
  five,
  fiveeighths,
  fiveinferior,
  fiveoldstyle,
  fivesuperior,
  fl,
  f_l,
  florin,
  four,
  fourinferior,
  fouroldstyle,
  foursuperior,
  fraction,
  g,
  gamma,
  germandbls,
  gradient,
  grave,
  greater,
  greaterequal,
  guillemotleft,
  guillemotright,
  guilsinglleft,
  guilsinglright,
  h,
  heart,
  hungarumlaut,
  hyphen,
  hypheninferior,
  hyphensuperior,
  i,
  iacute,
  icircumflex,
  idieresis,
  igrave,
  infinity,
  integral,
  integralbt,
  integralex,
  integraltp,
  intersection,
  iota,
  isuperior,
  j,
  k,
  kappa,
  l,
  lambda,
  less,
  lessequal,
  logicaland,
  logicalnot,
  logicalor,
  lozenge,
  lslash,
  lsuperior,
  m,
  macron,
  minus,
  minute,
  msuperior,
  mu,
  multiply,
  n,
  nine,
  nineinferior,
  nineoldstyle,
  ninesuperior,
  notelement,
  notequal,
  notsubset,
  nsuperior,
  ntilde,
  nu,
  numbersign,
  o,
  oacute,
  ocircumflex,
  odieresis,
  oe,
  ogonek,
  ograve,
  omega,
  omega1,
  omicron,
  one,
  onedotenleader,
  oneeighth,
  onefitted,
  onehalf,
  oneinferior,
  oneoldstyle,
  onequarter,
  onesuperior,
  onethird,
  ordfeminine,
  ordmasculine,
  oslash,
  osuperior,
  otilde,
  p,
  paragraph,
  parenleft,
  parenleftbt,
  parenleftex,
  parenleftinferior,
  parenleftsuperior,
  parenlefttp,
  parenright,
  parenrightbt,
  parenrightex,
  parenrightinferior,
  parenrightsuperior,
  parenrighttp,
  partialdiff,
  percent,
  period,
  periodcentered,
  periodinferior,
  periodsuperior,
  perpendicular,
  perthousand,
  phi,
  phi1,
  pi,
  plus,
  plusminus,
  product,
  propersubset,
  propersuperset,
  proportional,
  psi,
  q,
  question,
  questiondown,
  questiondownsmall,
  questionsmall,
  quotedbl,
  quotedblbase,
  quotedblleft,
  quotedblright,
  quoteleft,
  quoteright,
  quotesinglbase,
  quotesingle,
  r,
  radical,
  radicalex,
  reflexsubset,
  reflexsuperset,
  registered,
  registersans,
  registerserif,
  rho,
  ring,
  rsuperior,
  rupiah,
  s,
  scaron,
  second,
  section,
  semicolon,
  seven,
  seveneighths,
  seveninferior,
  sevenoldstyle,
  sevensuperior,
  sigma,
  sigma1,
  similar,
  six,
  sixinferior,
  sixoldstyle,
  sixsuperior,
  slash,
  space,
  spade,
  ssuperior,
  sterling,
  suchthat,
  summation,
  t,
  tau,
  therefore,
  theta,
  theta1,
  thorn,
  three,
  threeeighths,
  threeinferior,
  threeoldstyle,
  threequarters,
  threequartersemdash,
  threesuperior,
  tilde,
  trademark,
  trademarksans,
  trademarkserif,
  tsuperior,
  two,
  twodotenleader,
  twoinferior,
  twooldstyle,
  twosuperior,
  twothirds,
  u,
  uacute,
  ucircumflex,
  udieresis,
  ugrave,
  underscore,
  union,
  universal,
  upsilon,
  v,
  w,
  weierstrass,
  x,
  xi,
  y,
  yacute,
  ydieresis,
  yen,
  z,
  zcaron,
  zero,
  zeroinferior,
  zerooldstyle,
  zerosuperior,
  zeta,
  a100,
  a101,
  a102,
  a103,
  a104,
  a105,
  a106,
  a107,
  a108,
  a109,
  a10,
  a110,
  a111,
  a112,
  a117,
  a118,
  a119,
  a11,
  a120,
  a121,
  a122,
  a123,
  a124,
  a125,
  a126,
  a127,
  a128,
  a129,
  a12,
  a130,
  a131,
  a132,
  a133,
  a134,
  a135,
  a136,
  a137,
  a138,
  a139,
  a13,
  a140,
  a141,
  a142,
  a143,
  a144,
  a145,
  a146,
  a147,
  a148,
  a149,
  a14,
  a150,
  a151,
  a152,
  a153,
  a154,
  a155,
  a156,
  a157,
  a158,
  a159,
  a15,
  a160,
  a161,
  a162,
  a163,
  a164,
  a165,
  a166,
  a167,
  a168,
  a169,
  a16,
  a170,
  a171,
  a172,
  a173,
  a174,
  a175,
  a176,
  a177,
  a178,
  a179,
  a17,
  a180,
  a181,
  a182,
  a183,
  a184,
  a185,
  a186,
  a187,
  a188,
  a189,
  a18,
  a190,
  a191,
  a192,
  a193,
  a194,
  a195,
  a196,
  a197,
  a198,
  a199,
  a19,
  a1,
  a200,
  a201,
  a202,
  a203,
  a204,
  a205,
  a206,
  a20,
  a21,
  a22,
  a23,
  a24,
  a25,
  a26,
  a27,
  a28,
  a29,
  a2,
  a30,
  a31,
  a32,
  a33,
  a34,
  a35,
  a36,
  a37,
  a38,
  a39,
  a3,
  a40,
  a41,
  a42,
  a43,
  a44,
  a45,
  a46,
  a47,
  a48,
  a49,
  a4,
  a50,
  a51,
  a52,
  a53,
  a54,
  a55,
  a56,
  a57,
  a58,
  a59,
  a5,
  a60,
  a61,
  a62,
  a63,
  a64,
  a65,
  a66,
  a67,
  a68,
  a69,
  a6,
  a70,
  a71,
  a72,
  a73,
  a74,
  a75,
  a76,
  a77,
  a78,
  a79,
  a7,
  a81,
  a82,
  a83,
  a84,
  a85,
  a86,
  a87,
  a88,
  a89,
  a8,
  a90,
  a91,
  a92,
  a93,
  a94,
  a95,
  a96,
  a97,
  a98,
  a99,
  a9,
}
