// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

interface JSClass{
  initialize(): void;
  definePropertiesFromExtensions(extensions: object): void;
  className: string;
  $super: object;
  isSubclassOfClass(referenceClass: JSClass): boolean;
  initializeSubclass(subclass: JSClass): void;
  $extend(extensions: object, className: string): void;
}
interface JSClassConstructor{
  (className: string, superclass: JSClass, extensions: object): JSClass;
  (cls: JSClass): void;
  new (className: string, superclass: JSClass, extensions: object): JSClass;
  readonly prototype: JSClass;
  FromName(className: string): JSClass;
}
declare const JSClass: JSClassConstructor;

interface JSObject{
  init(): this | void
  initWithSpec(spec: JSSpec): this | void
  initWithSpecName(specName: string, bundle?: JSBundle): this | void | null
  awakeFromSpec(): void;
  $class: JSClass;
  isKindOfClass(referenceClass: JSClass): boolean;
  objectID: number;
  isEqual(other: JSObject): boolean;
  bind(binding: string, toObject: JSObject, keyPath: string, options?: {}): void;
  unbind(binding: string): void;
  didChangeValueForBinding(binding: string): void;
  addObserverForKeyPath(observer: JSObject, keyPath: string, options?: object, context?: any): void;
  removeObserverForKeyPath(observer: JSObject, keyPath: string, context?: void): void;
  observeValueForKeyPath(keyPath: string, ofObject: JSObject, change: object, context: any): void;
  valueForKey(key: string): any;
  valueForKeyPath(keyPath: string): any;
  setValueForKey(value: any, key: string): void;
  setValueForKeyPath(value: any, keyPath: string): void;
  canPerformAction(action: string, sender: any | null): boolean;
}
declare const JSObject: JSClass & {
  new (): JSObject;
  readonly prototype: JSObject;
  init<T>(this: { new(): T }): T;
  initWithSpec<T>(this: { new(): T }, spec: JSSpec): T;
  initWithSpecName<T>(this: { new(): T }, specName: string, bundle?: JSBundle): T | null;
}


declare class JSCustomProperty{
  define(cls: JSClass, propertyName: string, extensions: {}): void;
}

declare class JSDynamicProperty extends JSCustomProperty{
  constructor();
  constructor(privateName: string, intialValue: any);
  constructor(privateName: string, intialValue: any, getterName: string, setterName: string);
}
declare function JSDynamicProperty(): JSDynamicProperty;
declare function JSDynamicProperty(privateName: string, intialValue: any): JSDynamicProperty;
declare function JSDynamicProperty(privateName: string, intialValue: any, getterName: string, setterName: string): JSDynamicProperty;


declare class JSReadOnlyProperty extends JSCustomProperty{
  constructor();
  constructor(privateName: string, intialValue: any);
  constructor(privateName: string, intialValue: any, getterName: string);
}
declare function JSReadOnlyProperty(): JSReadOnlyProperty;
declare function JSReadOnlyProperty(privateName: string, intialValue: any): JSReadOnlyProperty;
declare function JSReadOnlyProperty(privateName: string, intialValue: any, getterName: string): JSReadOnlyProperty;


declare class JSLazyInitProperty extends JSCustomProperty{
  constructor(createMethodName: string);
  constructor(createMethod: (() => void));
  constructor(createMethodName: string, privatePropertyName: string);
  constructor(createMethod: (() => void), privatePropertyName: string);
}
declare function JSLazyInitProperty(createMethodName: string): JSLazyInitProperty;
declare function JSLazyInitProperty(createMethod: (() => void)): JSLazyInitProperty;
declare function JSLazyInitProperty(createMethodName: string, privatePropertyName: string): JSLazyInitProperty;
declare function JSLazyInitProperty(createMethod: (() => void), privatePropertyName: string): JSLazyInitProperty;


declare class JSOutlet extends JSCustomProperty{
  constructor();
}
declare function JSOutlet(): JSOutlet;


interface String{
  dataUsingEncoding(encoding: String.Encoding): JSData;
  utf8(): JSData;
  utf16be(): JSData;
  utf16le(): JSData;
  latin1(): JSData;
  unicodeIterator(startIndex?: number): UnicodeIterator;
  userPerceivedCharacterIterator(startIndex?: number): UserPerceivedCharacterIterator;
  unicodeAtIndex(index: number): UnicodeChar;
  rangeForUserPerceivedCharacterAtIndex(index: number): JSRange;
  rangeForWordAtIndex(index: number): JSRange;
  stringForWordAtIndex(index: number): string;
  indexOfWordEndAfterIndex(index: number): number;
  indexOfWordStartBeforeIndex(index: number): number;
  rangeForLineAtIndex(index: number): JSRange;
  stringByAppendingString(string: string): string;
  stringByReplacingCharactersInRangeWithString(range: JSRange, string: string): string;
  stringByDeletingCharactersInRange(range: JSRange): string;
  stringByMaskingWithCharacter(mask: string, userPerceived?: boolean): string;
  uppercaseString(): string;
  lowercaseString(): string;
  capitalizedString(): string;
  substringInRange(range: JSRange): string;
  trimmedSplit(splitOn: string): string[];
  splitAtIndex(index: number): string[];
  sprintf(...args: any[]): string;
  format(formatter: {}, args: any[]): string;
  leftPaddedString(padding: string, width: number): string;
  rightPaddedString(padding: string, width: number): string;
  replacingTemplateParameters(parameters: {}, open?: string, close?: string): string;
  fileExtension: string;
  removingFileExtension(): string;
  dataByDecodingBase64(): JSData;
  dataByDecodingBase64URL(): JSData;
  dataByDecodingHex(): JSData;
}
declare enum StringEncoding{
  utf8,
  utf16be,
  utf16le,
  iso8859_1,
  latin1,
}
declare namespace String{
  type Encoding = StringEncoding;
}
interface StringConstructor{
  initWithFormat<T>(this: { new(): T }, format: string, ...args: any[]): T;
  initWithData<T>(this: { new(): T }, data: JSData, encoding: String.Encoding): T;
  fromUnicode(code: UnicodeChar | number): void;
  readonly Encoding: typeof StringEncoding;
}

declare class JSAttributedString extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  static initWithString<T>(this: { new(): T }, string: string, attributes?: {}): T;
  initWithString(string: string, attributes?: {}): this | void
  static initWithAttributedString<T>(this: { new(): T }, attributedString: JSAttributedString, defaultAttributes?: {}): T;
  initWithAttributedString(attributedString: JSAttributedString, defaultAttributes?: {}): this | void
  static initWithAttachment<T>(this: { new(): T }, attachment: JSTextAttachment): T;
  initWithAttachment(attachment: JSTextAttachment): this | void
  static initWithAttachmentName<T>(this: { new(): T }, name: string, size: JSSize): T;
  initWithAttachmentName(name: string, size: JSSize): this | void
  static initFromDictionary<T>(this: { new(): T }, dictionary: JSAttributedString.AttributedStringDictionary | null): T | null;
  initFromDictionary(dictionary: JSAttributedString.AttributedStringDictionary | null): this | void | null
  static initWithHTML<T>(this: { new(): T }, html: string): T;
  initWithHTML(html: string): this | void
  static initWithHTML<T>(this: { new(): T }, html: string, options: JSAttributedString.HTMLParseOptions): T;
  initWithHTML(html: string, options: JSAttributedString.HTMLParseOptions): this | void
  string: string;
  rangeOfRunAtIndex(index: number): JSRange;
  attributesAtIndex(index: number): {};
  attributeAtIndex(attribute: string, index: number): {};
  longestRangeOfAttributeAtIndex(attributeName: string, index: number): JSRange;
  longestRangeOfAttributesAtIndex(attributeNames: string[], index: number): JSRange;
  setAttributesInRange(attributes: {}, range: JSRange): void;
  addAttributeInRange(attributeName: string, value: any, range: JSRange): void;
  addAttributesInRange(attributes: {}, range: JSRange): void;
  removeAttributeInRange(attributeName: string, range: JSRange): void;
  removeAttributesInRange(attributeNames: string[], range: JSRange): void;
  removeAllAttributesInRange(range: JSRange): void;
  appendString(string: string): void;
  appendAttributedString(attributedString: JSAttributedString): void;
  appendAttachment(attachment: JSTextAttachment): void;
  insertString(string: string, index: number): void;
  insertAttributedString(attributedString: JSAttributedString, index: number): void;
  insertAttachment(attachment: JSTextAttachment, index: number): void;
  deleteCharactersInRange(range: JSRange): void;
  replaceCharactersInRangeWithString(range: JSRange, string: JSRange): void;
  replaceCharactersInRangeWithAttributedString(range: JSRange, attributedString: JSRange): void;
  replaceFormat(formatArgument1: any, replacementAttributes1: {}, ...formatArgument2: any[]): void;
  attributedSubstringInRange(range: JSRange): JSAttributedString;
  dictionaryRepresentation(): JSAttributedString.AttributedStringDictionary;
}
declare namespace JSAttributedString{
  enum Attribute{
    font,
    textColor,
    backgroundColor,
    bold,
    italic,
    underline,
    strike,
    lineHeightMultiple,
    lineSpacing,
    paragraphSpacing,
    beforeParagraphSpacing,
    textAlignment,
    lineBreakMode,
    firstLineHeadIndent,
    headIndent,
    tailIndent,
    minimiumLineHeight,
    maskCharacter,
    attachment,
  }
  type AttributedStringDictionary = {
    string: string;
    runs: JSAttributedString.RunDictionary[];
  };
  type RunDictionary = {
    length: number;
    attributes: object;
  };
  type HTMLParseOptions = {
    preserveWhitespace: boolean | null;
    baseURL: JSURL | null;
  };
}

interface Uint8Array{
  hexStringRepresentation(): string;
  base64StringRepresentation(): string;
  base64StringRepresentation(maxLineWidth: number, omitPadding: boolean): string;
  base64URLStringRepresentation(): string;
  base64URLStringRepresentation(maxLineWidth: number): string;
  dataView(): DataView;
  nodeBuffer(): object;
  stringByDecodingUTF8(): string;
  stringByDecodingUTF16BE(): string;
  stringByDecodingUTF16LE(): string;
  stringByDecodingLatin1(): string;
  isEqual(other: JSData): boolean;
  dataByDecodingPercentEscapes(decodePlusAsSpace?: boolean): JSData;
  dataByEncodingPercentEscapes(reserved?: {}, encodeSpaceAsPlus?: boolean): JSData;
  zero(): void;
  copyTo(other: JSData, index: number): void;
  increasedByLength(length: number): void;
  subdataInRange(range: JSRange): JSData;
  truncatedToLength(length: number): JSData;
}
type JSData = Uint8Array;
declare namespace JSData{
  function initWithLength(length: number): JSData;
  function initWithBuffer(buffer: ArrayBuffer): JSData;
  function initWithChunks(chunks: JSData[]): JSData;
  function initWithArray(array: number[]): JSData;
  function initWithNodeBuffer(buffer: object): JSData;
  function initWithCopyOfData(data: JSData): JSData;
}

declare class UnicodeChar{
  constructor(code: number);
  code: number;
  utf16: string;
  alphabetic: boolean;
  ideographic: boolean;
  graphemeExtend: boolean;
  defaultIgnorableCodePoint: boolean;
  generalCategoryIsOtherLetter: boolean;
  generalCategoryIsConnectorPunctuation: boolean;
  generalCategoryIsSpacingMark: boolean;
  generalCategoryIsFormat: boolean;
  generalCategoryIsLineSeparator: boolean;
  generalCategoryIsParagraphSeparator: boolean;
  generalCategoryIsControl: boolean;
  generalCategoryIsUnassigned: boolean;
  generalCategoryIsSurrogate: boolean;
  lineBreakIsComplexContext: boolean;
  lineBreakIsInfixNumeric: boolean;
  lineBreakIsNumeric: boolean;
  lineBreakIsQuotation: boolean;
  isLineBreak: boolean;
  wordBreakIsKatakana: boolean;
  wordBreakIsExtend: boolean;
  wordBreakIsHebrewLetter: boolean;
  wordBreakCR: boolean;
  wordBreakLF: boolean;
  wordBreakNewline: boolean;
  wordBreakAHLetter: boolean;
  wordBreakALetter: boolean;
  wordBreakHebrewLetter: boolean;
  wordBreakKatakana: boolean;
  wordBreakRegionalIndicator: boolean;
  wordBreakSingleQuote: boolean;
  wordBreakDoubleQuote: boolean;
  wordBreakNumeric: boolean;
  wordBreakExtendedNumLet: boolean;
  wordBreakMidLetter: boolean;
  wordBreakMidNumLet: boolean;
  wordBreakMidNumLetQ: boolean;
  wordBreakMidNum: boolean;
  wordBreakExtend: boolean;
  wordBreakFormat: boolean;
  graphemeClusterBreakCR: boolean;
  graphemeClusterBreakLF: boolean;
  graphemeClusterBreakControl: boolean;
  graphemeClusterBreakExtend: boolean;
  graphemeClusterBreakRegionalIndicator: boolean;
  graphemeClusterBreakPrepend: boolean;
  graphemeClusterBreakSpacingMark: boolean;
  graphemeClusterBreakL: boolean;
  graphemeClusterBreakV: boolean;
  graphemeClusterBreakT: boolean;
  graphemeClusterBreakLV: boolean;
  graphemeClusterBreakLVT: boolean;
  scriptIsHiragana: boolean;
  scriptIsHebrew: boolean;
  scriptIsKatakana: boolean;
  hangulSyllableTypeIsL: boolean;
  hangulSyllableTypeIsV: boolean;
  hangulSyllableTypeIsT: boolean;
  hangulSyllableTypeIsLV: boolean;
  hangulSyllableTypeIsLVT: boolean;
}
declare function UnicodeChar(code: number): UnicodeChar;


declare class UnicodeIterator{
  character: UnicodeChar;
  increment(): void;
  decrement(): void;
  index: number;
  nextIndex: number;
  isWordBoundary: boolean;
  isWhiteSpace: boolean;
}

declare class UserPerceivedCharacterIterator{
  range: JSRange;
  utf16: string;
  firstCharacter: UnicodeChar;
  increment(): void;
  decrement(): void;
  index: number;
  nextIndex: number;
  isWordBoundary: boolean;
  isWhiteSpace: boolean;
  isMandatoryLineBreak: boolean;
}

declare class JSDate{
  static initWithTimeIntervalSince1970<T>(this: { new(): T }, timeInterval: number): T;
  initWithTimeIntervalSince1970(timeInterval: number): this | void
  static initWithTimeIntervalSinceNow<T>(this: { new(): T }, timeInterval: number): T;
  initWithTimeIntervalSinceNow(timeInterval: number): this | void
  static now: JSDate;
  static distantPast: JSDate;
  static distantFuture: JSDate;
  static unixEpoch: JSDate;
  addingTimeInterval(timeInterval: number): JSDate;
  timeIntervalSinceDate(other: JSDate): number;
  timeIntervalUntilDate(other: JSDate): number;
  timeIntervalSince1970: number;
  isEqual(other: JSDate): boolean;
  compare(other: JSDate): number;
  isPast(): boolean;
}

declare class JSDateFormatter extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  static initWithLocale<T>(this: { new(): T }, locale: JSLocale): T;
  initWithLocale(locale: JSLocale): this | void
  locale: JSLocale;
  calendar: JSCalendar;
  timezone: JSTimeZone;
  stringFromDate(date: JSDate): string;
  dateFormat: string;
  narrowEraSymbols: string[];
  abbreviatedEraSymbols: string[];
  fullEraSymbols: string[];
  narrowMonthSymbols: string[];
  abbreviatedMonthSymbols: string[];
  fullMonthSymbols: string[];
  narrowStandaloneMonthSymbols: string[];
  abbreviatedStandaloneMonthSymbols: string[];
  fullStandaloneMonthSymbols: string[];
  narrowWeekdaySymbols: string[];
  shortWeekdaySymbols: string[];
  abbreviatedWeekdaySymbols: string[];
  fullWeekdaySymbols: string[];
  narrowStandaloneWeekdaySymbols: string[];
  shortStandaloneWeekdaySymbols: string[];
  abbreviatedStandaloneWeekdaySymbols: string[];
  fullStandaloneWeekdaySymbols: string[];
  amSymbol: string[];
  pmSymbol: string[];
}

declare class JSCalendar extends JSObject{
  static initWithIdentifier<T>(this: { new(): T }, identifier: JSCalendar.Identifier): T;
  initWithIdentifier(identifier: JSCalendar.Identifier): this | void
  timezone: JSTimeZone;
  dateFromComponents(components: JSCalendar.Components): JSDate;
  dateByAddingComponents(components: JSCalendar.Components, toDate: JSDate): JSDate;
  dateFromISO8601String(): JSDate | null;
  componentsFromISO8601String(): JSCalendar.Components | null;
  componentsFromDate(units: number, date: JSDate, timezone?: JSTimeZone): JSCalendar.Components;
  componentsBetweenDates(units: number, date1: JSDate, date2: JSDate, timezone?: JSTimeZone): JSCalendar.Components;
}
declare namespace JSCalendar{
  enum Identifier{
    gregorian,
  }
  class Unit{
    static none: number;
    static calendar: number;
    static era: number;
    static year: number;
    static month: number;
    static day: number;
    static hour: number;
    static minute: number;
    static second: number;
    static millisecond: number;
    static weekday: number;
    static timezone: number;
  }
  type Components = {
    calendar?: JSCalendar | null;
    era?: number | null;
    year?: number | null;
    month?: number | null;
    day?: number | null;
    hour?: number | null;
    minute?: number | null;
    second?: number | null;
    millisecond?: number | null;
    weekday?: number | null;
    timezone?: JSTimeZone | null;
  };
  enum Weekday{
    sunday,
    monday,
    tuesday,
    wednesday,
    thursday,
    friday,
    saturday,
  }
}

declare class JSLocale extends JSObject{
  static initWithIdentifier<T>(this: { new(): T }, identifier: string): T | null;
  initWithIdentifier(identifier: string): this | void | null
  static current: JSLocale;
  preferredLanguages: string[];
  identifier: string;
  identifierWithoutExtensions: string;
  languageCode: string;
  regionCode: string;
  scriptCode: string;
  extensions: string[];
  decimalSeparator: string;
  groupingSeparator: string;
  calendarIdentifier: JSCalendar.Identifier;
}

declare class JSTimeZone extends JSObject{
  static knownTimeZoneIdentifiers: string[];
  static importZoneInfo(info: {}): void;
  static initWithIdentifier<T>(this: { new(): T }, identifier: string | null): T | null;
  initWithIdentifier(identifier: string | null): this | void | null
  static initWithTimeIntervalFromUTC<T>(this: { new(): T }, timeInterval: number, abbreviation: string): T;
  initWithTimeIntervalFromUTC(timeInterval: number, abbreviation: string): this | void
  static local: JSTimeZone;
  static utc: JSTimeZone;
  static changeLocalTimeZone(identifier: string): void;
  static systemTimeZoneIdentifier: void;
  abbreviation: string;
  abbreviationForDate(date: JSDate): string;
  timeIntervalFromUTC: number;
  timeIntervalFromUTCForDate(date: JSDate): string;
  isDaylightSavingsTime: boolean;
  isDaylightSavingsTimeForDate(date: JSDate): boolean;
  nextDaylightSavingsTransition: JSDate;
  nextDaylightSavingsTransitionAfterDate(date: JSDate): JSDate;
}

declare class JSTimeInterval{
  static milliseconds(milliseconds: number): number;
  static seconds(seconds: number): number;
  static minutes(minutes: number): number;
  static hours(hours: number): number;
}

declare class JSRange{
  constructor(location: number, length: number);
  constructor(range: JSRange);
  location: number;
  length: number;
  end: number;
}
declare function JSRange(location: number, length: number): JSRange;
declare function JSRange(range: JSRange): JSRange;


declare class JSIndexPath{
  constructor(section: number, row: number);
  constructor(components: number[]);
  constructor(indexPath: JSIndexPath);
  section: number;
  row: number;
  isEqual(otherIndexPath: JSIndexPath): boolean;
  isLessThan(otherIndexPath: JSIndexPath): boolean;
  isLessThanOrEqual(otherIndexPath: JSIndexPath): boolean;
  isGreaterThan(otherIndexPath: JSIndexPath): boolean;
  isGreaterThanOrEqual(otherIndexPath: JSIndexPath): boolean;
  compare(otherIndexPath: JSIndexPath): number;
  incremented(): JSIndexPath;
  decremented(): JSIndexPath;
}
declare function JSIndexPath(section: number, row: number): JSIndexPath;
declare function JSIndexPath(components: number[]): JSIndexPath;
declare function JSIndexPath(indexPath: JSIndexPath): JSIndexPath;


declare class JSIndexSet{
  constructor();
  constructor(otherIndexSet: void);
  constructor();
}
declare function JSIndexSet(): JSIndexSet;
declare function JSIndexSet(otherIndexSet: void): JSIndexSet;
declare function JSIndexSet(): JSIndexSet;


declare class JSContext extends JSObject{
  beginPath(): void;
  closePath(): void;
  moveToPoint(x: number, y: number): void;
  addLineToPoint(x: number, y: number): void;
  addRect(rect: JSRect): void;
  addRoundedRect(rect: JSRect, cornerRadius: number): void;
  addEllipseInRect(rect: JSRect): void;
  addArc(center: JSPoint, radius: number, startAngle: number, endAngle: number, clockwise?: boolean): void;
  addArcUsingTangents(tangent1End: JSPoint, tangent2End: JSPoint, radius: number): void;
  addCurveToPoint(point: JSPoint, control1: JSPoint, control2: JSPoint): void;
  addQuadraticCurveToPoint(point: JSPoint, control: JSPoint): void;
  addPath(path: JSPath): void;
  setFillColor(fillColor: JSColor): void;
  setStrokeColor(strokeColor: JSColor): void;
  setShadow(offset: JSPoint, blur: number, color: JSColor): void;
  setAlpha(alpha: number): void;
  setLineWidth(lineWidth: number): void;
  setLineCap(lineCap: JSContext.LineCap): void;
  setLineJoin(lineJoin: JSContext.LineJoin): void;
  setMiterLimit(miterLimit: number): void;
  setLineDash(phase: number, lengths: number[]): void;
  drawPath(drawingMode: JSContext.DrawingMode): void;
  fillPath(fillRule?: JSContext.FillRule): void;
  strokePath(): void;
  clip(fillRule?: JSContext.FillRule): void;
  setTextMatrix(textMatrix: JSAffineTransform): void;
  setCharacterSpacing(spacing: number): void;
  setFont(font: JSFont): void;
  setTextDrawingMode(textDrawingMode: JSContext.DrawingMode): void;
  showText(text: string): void;
  showGlyphs(glyphs: number[]): void;
  scaleBy(sx: number, sy: number): void;
  rotateBy(radians: number): void;
  rotateByDegrees(degrees: number): void;
  translateBy(tx: number, ty: number): void;
  concatenate(transform: JSAffineTransform): void;
  drawImage(image: JSImage, rect: JSRect): void;
  drawLinearGradient(gradient: JSGradient, rect: JSRect): void;
  save(): void;
  restore(): void;
  fillRect(rect: JSRect): void;
  strokeRect(rect: JSRect): void;
  fillRoundedRect(rect: JSRect, radius: number): void;
  strokeRoundedRect(rect: JSRect, radius: number): void;
  fillEllipseInRect(rect: JSRect): void;
  strokeEllipseRect(rect: JSRect): void;
  fillMaskedRect(rect: JSRect, maskImage: JSImage): void;
}
declare namespace JSContext{
  enum DrawingMode{
    fill,
    evenOddFill,
    stroke,
    fillStroke,
    evenOddFillStroke,
  }
  enum FillRule{
    winding,
    evenOdd,
  }
  enum LineCap{
    butt,
    round,
    square,
  }
  enum LineJoin{
    round,
    bevel,
    miter,
  }
}

declare class JSPoint{
  constructor(x: number, y: number);
  constructor(other: JSPoint);
  static Zero: JSPoint;
  static UnitCenter: JSPoint;
  static initWithSpec(spec: JSSpec): void;
  x: number;
  y: number;
  adding(other: JSPoint): JSPoint;
  subtracting(other: JSPoint): JSPoint;
  distanceToPoint(other: JSPoint): number;
  angleToPoint(other: JSPoint): number;
}
declare function JSPoint(x: number, y: number): JSPoint;
declare function JSPoint(other: JSPoint): JSPoint;


declare class JSSize{
  constructor(width: number, height: number);
  constructor(other: JSSize);
  static Zero: JSSize;
  static initWithSpec(spec: JSSpec): void;
  width: number;
  height: number;
}
declare function JSSize(width: number, height: number): JSSize;
declare function JSSize(other: JSSize): JSSize;


declare class JSRect{
  constructor(x: number, y: number, width: number, height: number);
  constructor(origin: JSPoint, size: JSSize);
  constructor(other: JSRect);
  static Zero: JSRect;
  static initWithSpec(spec: JSSpec): void;
  origin: JSPoint;
  size: JSSize;
  center: JSPoint;
  containsPoint(point: JSPoint): boolean;
  intersectsRect(other: JSRect): boolean;
  rectWithInsets(insets: JSInsets): JSRect;
  rectWithInsets(top: number, left?: number, bottom?: number, right?: number): JSRect;
}
declare function JSRect(x: number, y: number, width: number, height: number): JSRect;
declare function JSRect(origin: JSPoint, size: JSSize): JSRect;
declare function JSRect(other: JSRect): JSRect;


declare class JSInsets{
  constructor(top: number, left: number, bottom: number, right: number);
  constructor(all: number);
  constructor(topAndBottom: number, leftAndRight: number);
  constructor(other: JSInsets);
  static Zero: JSInsets;
  static initWithSpec(spec: JSSpec): void;
  top: number;
  left: number;
  bottom: number;
  right: number;
  width: number;
  height: number;
  insetsWithInsets(insets: JSInsets): JSInsets;
  negative(): JSInsets;
}
declare function JSInsets(top: number, left: number, bottom: number, right: number): JSInsets;
declare function JSInsets(all: number): JSInsets;
declare function JSInsets(topAndBottom: number, leftAndRight: number): JSInsets;
declare function JSInsets(other: JSInsets): JSInsets;


declare class JSAffineTransform{
  constructor(a: number, b: number, c: number, d: number, tx: number, ty: number);
  constructor(other: JSAffineTransform);
  static Identity: JSAffineTransform;
  static Scaled(sx: number, sy: number): JSAffineTransform;
  static Translated(tx: number, ty: number): JSAffineTransform;
  static Rotated(radians: number): JSAffineTransform;
  static RotatedDegrees(degrees: number): JSAffineTransform;
  static initWithSpec(spec: JSSpec): void;
  a: number;
  b: number;
  c: number;
  d: number;
  tx: number;
  ty: number;
  convertPointFromTransform(point: JSPoint): JSPoint;
  convertPointToTransform(point: JSPoint): JSPoint;
  scaledBy(sx: number, sy: number): JSAffineTransform;
  translatedBy(tx: number, ty: number): JSAffineTransform;
  rotatedBy(radians: number): JSAffineTransform;
  rotatedByDegrees(degrees: number): JSAffineTransform;
  concatenatedWith(transform: JSAffineTransform): JSAffineTransform;
  inverse(): JSAffineTransform;
  isEqual(other: JSAffineTransform): boolean;
  isIdentity(): boolean;
  isRotated(): boolean;
}
declare function JSAffineTransform(a: number, b: number, c: number, d: number, tx: number, ty: number): JSAffineTransform;
declare function JSAffineTransform(other: JSAffineTransform): JSAffineTransform;


declare class JSColor extends JSObject{
  static initWithSpaceAndComponents<T>(this: { new(): T }, space: JSColorSpace, components: number[]): T;
  initWithSpaceAndComponents(space: JSColorSpace, components: number[]): this | void
  static initWithRGBA<T>(this: { new(): T }, red: number, green: number, blue: number, alpha?: number): T;
  initWithRGBA(red: number, green: number, blue: number, alpha?: number): this | void
  static initWithRGBAHexString<T>(this: { new(): T }, hexString: string | null): T | null;
  initWithRGBAHexString(hexString: string | null): this | void | null
  static initWithHSVA<T>(this: { new(): T }, hue: number, saturation: number, value: number, alpha?: number): T;
  initWithHSVA(hue: number, saturation: number, value: number, alpha?: number): this | void
  static initWithHSLA<T>(this: { new(): T }, hue: number, saturation: number, lightness: number, alpha?: number): T;
  initWithHSLA(hue: number, saturation: number, lightness: number, alpha?: number): this | void
  static initWithWhite<T>(this: { new(): T }, white: number, alpha?: number): T;
  initWithWhite(white: number, alpha?: number): this | void
  static initWithBlendedColor<T>(this: { new(): T }, base: JSColor, other: JSColor, blendPercentage: number): T;
  initWithBlendedColor(base: JSColor, other: JSColor, blendPercentage: number): this | void
  static initWithUIStyles<T>(this: { new(): T }, lightColor: JSColor, darkColor: JSColor, lightContrastColor: JSColor, darkContrastColor: JSColor): T;
  initWithUIStyles(lightColor: JSColor, darkColor: JSColor, lightContrastColor: JSColor, darkContrastColor: JSColor): this | void
  static initWithUIStyles<T>(this: { new(): T }, lightColor: JSColor, darkColor: JSColor): T;
  initWithUIStyles(lightColor: JSColor, darkColor: JSColor): this | void
  static initFromDictionary<T>(this: { new(): T }, dictionary: {}): T | null;
  initFromDictionary(dictionary: {}): this | void | null
  static clear: JSColor;
  static white: JSColor | number;
  static black: JSColor;
  static red: JSColor | number;
  static green: JSColor | number;
  static blue: JSColor | number;
  static background: JSColor;
  static shadedBackground: JSColor;
  static secondaryShadedBackground: JSColor;
  static separator: JSColor;
  static secondarySeparator: JSColor;
  static text: JSColor;
  static secondaryText: JSColor;
  static highlight: JSColor;
  static mutedHighlight: JSColor;
  static highlightedText: JSColor;
  static placeholderText: JSColor;
  static destructive: JSColor;
  static controlBackground: JSColor;
  static controlBorder: JSColor;
  static controlTitle: JSColor;
  static activeControlBackground: JSColor;
  static activeControlBorder: JSColor;
  static activeControlTitle: JSColor;
  static selectedControlBackground: JSColor;
  static selectedControlBorder: JSColor;
  static selectedControlTitle: JSColor;
  static activeSelectedControlBackground: JSColor;
  static activeSelectedControlBorder: JSColor;
  static activeSelectedControlTitle: JSColor;
  static disabledControlBackground: JSColor;
  static disabledControlBorder: JSColor;
  static disabledControlTitle: JSColor;
  static controlShadow: JSColor;
  static window: JSColor;
  static windowShadow: JSColor;
  static toolbarTitle: JSColor;
  static tooltip: JSColor;
  static tooltipText: JSColor;
  static tooltipBorder: JSColor;
  static tooltipShadow: JSColor;
  static menuBar: JSColor;
  static menuBarText: JSColor;
  static menu: JSColor;
  static menuShadow: JSColor;
  space: JSColorSpace;
  components: number[];
  alpha: number;
  rgbaColor(): JSColor;
  grayColor(): JSColor;
  luminance: number;
  contrastRatioWithColor(otherColor: JSColor): number;
  colorWithAlpha(alpha: number): JSColor;
  colorDarkenedByPercentage(darkenPercentage: number): JSColor;
  colorLightenedByPercentage(lightenPercentage: number): JSColor;
  colorByBlendingColor(other: JSColor, blendPercentage: number): JSColor;
  rgbaHexStringRepresentation(): string;
  dictionaryRepresentation(): {};
  static contentType: string;
  static initWithSpaceAndComponents<T>(this: { new(): T }, colorSpace: JSColor.SpaceIdentifier, components: number[]): T;
  initWithSpaceAndComponents(colorSpace: JSColor.SpaceIdentifier, components: number[]): this | void
  colorSpace: JSColor.SpaceIdentifier;
  hue: number;
  saturation: number;
  lightness: number;
}
declare namespace JSColor{
  enum SpaceIdentifier{
    rgb,
    gray,
    rgba,
    hsl,
    hsla,
    graya,
  }
}

declare class JSColorSpace extends JSObject{
  static rgb: JSColorSpace;
  static gray: JSColorSpace;
  static ui: JSNamedColorSpace;
  numberOfComponents: number;
}

declare class JSNamedColorSpace extends JSColorSpace{
  setColorForName(name: string, color: JSColor): JSColor;
}

declare class JSCubicBezier{
  constructor(p1: JSPoint, cp1: JSPoint, cp2: JSPoint, p2: JSPoint);
  constructor(other: JSCubicBezier);
  p1: JSPoint;
  cp1: JSPoint;
  cp2: JSPoint;
  p2: JSPoint;
  boundingPoints(): JSPoint[];
  pointAtInterval(interval: number): JSPoint;
  intervalsForX(x: number): number[];
}
declare function JSCubicBezier(p1: JSPoint, cp1: JSPoint, cp2: JSPoint, p2: JSPoint): JSCubicBezier;
declare function JSCubicBezier(other: JSCubicBezier): JSCubicBezier;


declare class JSGradient extends JSObject{
  static initWithStops<T>(this: { new(): T }, position1: number, ...color1: JSColor[]): T;
  initWithStops(position1: number, ...color1: JSColor[]): this | void
  static initWithColors<T>(this: { new(): T }, colors: JSColor[]): T;
  initWithColors(colors: JSColor[]): this | void
  static gradientBetweenColors(color1: JSColor, color2: JSColor): JSGradient;
  addStop(position: number, color: JSColor): void;
  start: JSPoint;
  end: JSPoint;
}

declare class JSImage extends JSObject{
  static initWithResourceName<T>(this: { new(): T }, name: string, bundle?: JSBundle): T | null;
  initWithResourceName(name: string, bundle?: JSBundle): this | void | null
  static initWithData<T>(this: { new(): T }, data: JSData, size: JSSize, scale?: number): T;
  initWithData(data: JSData, size: JSSize, scale?: number): this | void
  static initWithURL<T>(this: { new(): T }, url: JSURL, size: JSSize, scale?: number): T;
  initWithURL(url: JSURL, size: JSSize, scale?: number): this | void
  size: JSSize;
  scale: number;
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
  renderMode: JSImage.RenderMode;
  imageWithRenderMode(renderMode: JSImage.RenderMode): JSImage;
  stretchableImageWithCapSizes(leftCapWidth: number, topCapWidth?: number, rightCapWidth?: number, bottomCapWidth?: number): void;
}
declare namespace JSImage{
  enum RenderMode{
    automatic,
    original,
    template,
  }
}

declare class JSPath extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  copy(): JSPath;
  empty: boolean;
  currentPoint: JSPoint;
  boundingRect: JSRect | null;
  moveToPoint(point: JSPoint, transform?: JSAffineTransform): void;
  addLineToPoint(point: JSPoint, transform?: JSAffineTransform): void;
  addCurveToPoint(point: JSPoint, controlPoint1: JSPoint, controlPoint2: JSPoint, transform?: JSAffineTransform): void;
  addRect(rect: JSRect, transform?: JSAffineTransform): void;
  addRoundedRect(rect: JSRect, cornerRadius: number, transform?: JSAffineTransform): void;
  addEllipseInRect(rect: JSRect, transform?: JSAffineTransform): void;
  addArc(center: JSPoint, radius: number, startAngle: number, endAngle: number, clockwise?: boolean, transform?: JSAffineTransform): void;
  addArcUsingTangents(tangent1End: JSPoint, tangent2End: JSPoint, radius: number, transform?: JSAffineTransform): void;
  closeSubpath(): void;
  containsPoint(point: JSPoint, fillRule?: JSContext.FillRule, transform?: JSAffineTransform): boolean;
}

declare class JSFileManager extends JSObject{
  static shared: JSFileManager;
  static initWithIdentifier<T>(this: { new(): T }, identifier: string): T;
  initWithIdentifier(identifier: string): this | void
  open(completion: (success: boolean) => void, target?: any): void;
  open(): void;
  temporaryDirectoryURL: JSURL;
  persistentContainerURL: JSURL;
  urlForPath(path: string): JSURL;
  pathForURL(url: JSURL): string;
  relativePathFromURL(url: JSURL, toURL: JSURL): string;
  isFileURL(url: JSURL): boolean;
  itemExistsAtURL(url: JSURL, completion: (exists: boolean) => void, target?: any): void;
  itemExistsAtURL(url: JSURL): Promise<boolean>;
  attributesOfItemAtURL(url: JSURL, completion: (attributes: JSFileManager.Attributes | null) => void, target?: any): void;
  attributesOfItemAtURL(url: JSURL): Promise<JSFileManager.Attributes>;
  stateOfItemAtURL(url: JSURL): JSFileManager.State | null;
  createDirectoryAtURL(url: JSURL, completion: (success: boolean) => void, target?: any): void;
  createDirectoryAtURL(url: JSURL): void;
  createFileAtURL(url: JSURL, contents: JSData, completion: (success: boolean) => void, target?: any): void;
  createFileAtURL(url: JSURL, contents: JSData): void;
  contentsAtURL(url: JSURL, completion: (contents: JSData | null) => void, target?: any): void;
  contentsAtURL(url: JSURL): void;
  contentsOfDirectoryAtURL(url: JSURL, completion: (items: JSFileManager.Item[] | null) => void, target?: any): void;
  contentsOfDirectoryAtURL(url: JSURL): void;
  moveItemAtURL(url: JSURL, toURL: JSURL, completion: (success: boolean) => void, target?: any): void;
  moveItemAtURL(url: JSURL, toURL: JSURL): void;
  copyItemAtURL(url: JSURL, toURL: JSURL, completion: (success: boolean) => void, target?: any): void;
  copyItemAtURL(url: JSURL, toURL: JSURL): void;
  removeItemAtURL(url: JSURL, completion: (success: boolean) => void, target?: any): void;
  removeItemAtURL(url: JSURL): void;
  createLinkAtURL(url: JSURL, toURL: JSURL, completion: (success: boolean) => void, target?: any): void;
  createLinkAtURL(url: JSURL, toURL: JSURL): void;
  createSymbolicLinkAtURL(url: JSURL, toURL: JSURL, completion: (success: boolean) => void, target?: any): void;
  createSymbolicLinkAtURL(url: JSURL, toURL: JSURL): void;
  destinationOfSymbolicLinkAtURL(url: JSURL, completion: (destinationURL: JSURL | null) => void, target?: any): void;
  destinationOfSymbolicLinkAtURL(url: JSURL): void;
  addObserverForURL(url: JSURL, name: JSFileManager.Notification, callback: (notification: JSNotification) => void, target?: any): number;
  removeObseverForURL(url: JSURL, name: JSFileManager.Notification, observerID: number): void;
  makeExecutableAtURL(url: JSURL, completion: (success: boolean) => void, target?: any): void;
  makeExecutableAtURL(url: JSURL): void;
}
declare namespace JSFileManager{
  enum ItemType{
    directory,
    file,
    symbolicLink,
    other,
  }
  type Attributes = {
    itemType: JSFileManager.ItemType;
    created: number;
    updated: number;
  };
  type State = {
    downloading: boolean;
    downloadedPercent: number | null;
    uploading: boolean;
    uploadedPercent: number;
  };
  type Item = {
    url: JSURL;
    name: string;
    itemType: JSFileManager.ItemType;
  };
  enum Notification{
    directoryDidAddItem,
    directoryDidRemoveItem,
    itemDidChangeState,
  }
}

declare class JSFile extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData, name: string, contentType: JSMediaType): T;
  initWithData(data: JSData, name: string, contentType: JSMediaType): this | void
  close(): void;
  name: string;
  contentType: JSMediaType | null;
  size: number;
  readData(completion: (data: JSData | null) => void, target: object): void;
  readData(): void;
  url: JSURL;
}

declare class JSFileEnumerator extends JSObject{
  next(callback: (directory: string, file: JSFile | null) => void, target?: any): void;
  enumerate(itemCallback: (directory: string, file: JSFile) => void, doneCallback: () => void, target?: any): void;
  single(callback: (file: JSFile | null) => void, target?: any): void;
  all(callback: (directory: JSFileEnumerator.Entry[]) => void, target?: any): void;
}
declare namespace JSFileEnumerator{
  type Entry = {
    directory: string;
    file: JSFile;
  };
}

declare class JSBundle extends JSObject{
  static mainBundle: JSBundle;
  static initWithIdentifier<T>(this: { new(): T }, identifier: string): T;
  initWithIdentifier(identifier: string): this | void
  info: {};
  metadataForResourceName(name: string): JSBundle.Metadata;
  metadataForResourceName(name: string, ext: string): JSBundle.Metadata;
  metadataForResourceName(name: string, ext: string, subdirectory: string): JSBundle.Metadata;
  getResourceData(metadata: JSBundle.Metadata, completion: (data: JSData) => void, target?: object): void;
  getResourceData(metadata: JSBundle.Metadata): Promise<JSData>;
  fileForResourceName(name: string): JSFile;
  fileForResourceName(name: string, ext: string): JSFile;
  fileForResourceName(name: string, ext: string, subdirectory: string): JSFile;
  localizedString(key: string, table?: string, locale?: JSLocale): string;
  localizedStringForInfoKey(infoKey: string): string;
}
declare namespace JSBundle{
  type Metadata = {
    byte_size: number;
    mimetype: string;
    hash: string;
  };
}

declare class JSSpec extends JSObject{
  static initWithResource<T>(this: { new(): T }, resource: string, bundle?: JSBundle): T | null;
  initWithResource(resource: string, bundle?: JSBundle): this | void | null
  initializeFilesOwner(filesOwner: JSObject): boolean;
  filesOwner: JSObject;
  valueForKey(key: string): any;
  valueForKey(key: string, type: JSClass): any;
  valueForKey(key: string, enum_: object): any;
  stringValue: string | null;
  numberValue: string | null;
  length: number;
}

declare class JSUserDefaults extends JSObject{
  static shared: JSUserDefaults;
  static initWithIdentifier<T>(this: { new(): T }, identifier: string): T;
  initWithIdentifier(identifier: string): this | void
  open(completion: (success: boolean) => void, target?: any): void;
  open(): Promise<void>;
  close(completion: (success: boolean) => void, target?: any): void;
  close(): Promise<void>;
  registerDefaults(defaults: {}): void;
  valueForKey(key: string): any;
  setValueForKey(value: any, key: string): void;
}

declare class JSArguments extends JSObject{
  static initWithOptions<T>(this: { new(): T }, options: {}): T;
  initWithOptions(options: {}): this | void
  addOption(): void;
  parse(argv: string[]): void;
  parseQueryString(queryString: string, positional: string[]): void;
  helpString(): string;
}
declare namespace JSArguments{
  type Option = {
    kind: JSArguments.Kind;
    multiple: boolean;
    default: any;
    valueType: JSArguments.ValueType;
    shortcut: string;
    allowed: string[];
    help: string;
  };
  enum Kind{
    default,
    flag,
    positional,
    unknown,
  }
  enum ValueType{
    string,
    integer,
  }
}

declare class JSRunLoop extends JSObject{
  static main: JSRunLoop;
  schedule(action: (() => void), target: object, ...args: any[]): void;
}

declare class JSUndoManager extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  canUndo: boolean;
  canRedo: boolean;
  registerUndo(target: object, action: (() => void), ...args: any[]): void;
  beginUndoGrouping(): void;
  endUndoGrouping(): void;
  clear(): void;
  maximumNumberOfUndos: number;
  undo(): void;
  redo(): void;
  setActionName(name: string): void;
  undoActionName: string;
  redoActionName: string;
  titleForUndoMenuItem: string;
  titleForRedoMenuItem: string;
}

declare class JSNotificationCenter extends JSObject{
  static shared: JSNotificationCenter;
  static init<T>(this: { new(): T }): T;
  init(): this | void
  postNotification(notification: JSNotification): void;
  post(name: string, sender: JSObject, userInfo?: any): void;
  addObserver(name: string, sender: JSObject | null, callback: (notification: JSNotification) => void, target?: object): number;
  removeObserver(name: string, observer: number): void;
}

declare class JSNotification extends JSObject{
  static initWithName<T>(this: { new(): T }, name: string, sender: JSObject, userInfo?: any): T;
  initWithName(name: string, sender: JSObject, userInfo?: any): this | void
  name: string;
  sender: JSObject;
  userInfo: any;
}

declare class JSEnvironment extends JSObject{
  current: JSEnvironment;
  static initWithData<T>(this: { new(): T }, data: JSData): T;
  initWithData(data: JSData): this | void
  static initWithDictionary<T>(this: { new(): T }, variables: {}): T;
  initWithDictionary(variables: {}): this | void
  get(name: string): string;
  get(name: string, defaultValue: any): string;
  stringForName(name: string): string | null;
  booleanForName(name: string): boolean;
  urlForName(name: string): JSURL | null;
  integerForName(name: string): number | null;
  base64DataForName(name: string): JSURL | null;
  base64URLDataForName(name: string): JSURL | null;
  hexDataForName(name: string): JSURL | null;
}

declare class JSObjectGraph extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  object(id: string, completion: (object: object | null, error: Error | null) => void, target?: object): void;
  object(id: string): void;
  objects(ids: string[], completion: (objects: object[]) => void, target?: object): void;
  objects(ids: string): void;
  loadObjetForID(id: string, completion: (object: object | null) => void): void;
  addObjectForID(object: object, id: string): void;
}

declare interface JSObjectGraphLoading{
  awakeInGraph?(graph: JSObjectGraph): Promise<void> | null;
}

declare class JSLog{
  constructor(subsystem: string, category: string);
  debug(message: string, ...args: any[]): void;
  info(message: string, ...args: any[]): void;
  log(message: string, ...args: any[]): void;
  warn(message: string, ...args: any[]): void;
  error(message: string, ...args: any[]): void;
  multiline(level: JSLog.Level, message: string): void;
  any: string;
  static configure(options: JSLog.Congfiguration, level: JSLog.Level, subsystem?: string, category?: string): void;
  static addHandler(handler: JSLogHandler, level: JSLog.Level, subsystem?: string, category?: string): void;
  static addHandler(handler: (record: JSLogRecord) => void, level: JSLog.Level, subsystem?: string, category?: string): void;
  static format(record: JSLogRecord): string;
  static formatted(records: JSLogRecord[]): string[];
  static getRecords(): JSLogRecord[];
}
declare namespace JSLog{
  enum Level{
    debug,
    info,
    log,
    warn,
    error,
  }
  type Congfiguration = {
    enabled?: boolean | null;
    print?: boolean | null;
    console?: Console | null;
  };
}
declare function JSLog(subsystem: string, category: string): JSLog;


declare type JSLogRecord = {
  level: JSLog.Level;
  timestamp: number;
  subsystem: string;
  category: string;
  message: string;
  args: any[];
};

declare interface JSLogHandler{
  handleLog(record: JSLogRecord): void;
}

declare class JSURL extends JSObject{
  static initWithString<T>(this: { new(): T }, string: string | null): T | null;
  initWithString(string: string | null): this | void | null
  static initWithString<T>(this: { new(): T }, string: string | null, baseURL: JSURL): T | null;
  initWithString(string: string | null, baseURL: JSURL): this | void | null
  static initWithURL<T>(this: { new(): T }, url: JSURL): T;
  initWithURL(url: JSURL): this | void
  static initWithData<T>(this: { new(): T }, data: JSData | null): T | null;
  initWithData(data: JSData | null): this | void | null
  encodedString: string;
  scheme: string;
  host: string;
  port: number;
  path: string;
  pathComponents: string[];
  lastPathComponent: string;
  fileExtension: string;
  hasDirectoryPath: boolean;
  encodedQuery: JSData;
  query: JSFormFieldMap;
  encodedPathAndQuery: string;
  encodedFragment: JSData;
  fragment: string;
  setFragmentQuery(query: JSFormFieldMap): void;
  encodedUserInfo: JSData;
  isAbsolute: boolean;
  resolveToBaseURL(baseURL: JSURL): void;
  resolvingToBaseURL(baseURL: JSURL): JSURL;
  encodedStringRelativeTo(baseURL: JSURL): string;
  appendPathCompoment(component: string, isDirectory?: boolean): void;
  appendingPathCompoment(component: string, isDirectory?: boolean): JSURL;
  appendPathCompoments(components: string[], isFinalDirectory?: boolean): void;
  appendingPathCompoments(components: string[], isFinalDirectory?: boolean): JSURL;
  appendFileExtension(ext: string): void;
  appendingFileExtension(ext: string): JSURL;
  removeFileExtension(): void;
  removingFileExtension(): JSURL;
  removeLastPathComponent(): void;
  removingLastPathComponent(): JSURL;
  setPathComponents(components: string[], isFinalDirectory: boolean): void;
  settingHasDirectoryPath(hasDirectoryPath: boolean): void;
  standardize(): void;
  standardized(): JSURL;
  copy(): JSURL;
  isEqual(other: JSURL): boolean;
}

declare class JSURLSession extends JSObject{
  static shared: JSURLSession;
  delegate: JSURLSessionDelegate;
  dataTaskWithURL(url: JSURL, completion: (error: Error) => void, target?: any): JSURLSessionDataTask;
  dataTaskWithURL(url: JSURL): JSURLSessionDataTask;
  dataTaskWithRequest(request: JSURLRequest, completion: (error: Error) => void, target?: any): JSURLSessionDataTask;
  dataTaskWithRequest(request: JSURLRequest): JSURLSessionDataTask;
  uploadTaskWithRequest(request: JSURLRequest, data: JSData, completion: (error: Error) => void, target?: any): JSURLSessionUploadTask;
  uploadTaskWithRequest(request: JSURLRequest, data: JSData): JSURLSessionUploadTask;
  streamTaskWithURL(url: JSURL, requestedProtocols: string[]): JSURLSessionStreamTask;
}

declare interface JSURLSessionDelegate{
  urlSessionTaskDidSendBodyData?(session: JSURLSession, task: JSURLSessionTask, totalSent: number, totalExpected: number): void;
  urlSessionTaskDidReceiveBodyData?(session: JSURLSession, task: JSURLSessionTask, totalReceived: number, totalExpected: number): void;
  urlSessionTaskDidComplete?(session: JSURLSession, task: JSURLSessionTask, error: Error): void;
  urlSessionTaskDidOpenStream?(session: JSURLSession, task: JSURLSessionStreamTask): void;
  urlSessionTaskDidCloseStream?(session: JSURLSession, task: JSURLSessionStreamTask): void;
  urlSessionTaskDidReceiveStreamData?(session: JSURLSession, task: JSURLSessionTask, data: JSData): void;
  urlSessionTaskDidReceiveStreamError?(session: JSURLSession, task: JSURLSessionTask): void;
}

declare class JSURLSessionTask extends JSObject{
  session: JSURLSession;
  resume(): Promise<JSURLResponse> | null;
  cancel(): void;
  progressDelegate: JSURLSessionTaskProgressDelegate;
  error: Error;
}

declare interface JSURLSessionTaskProgressDelegate{
  taskDidSendBodyData?(task: JSURLSessionTask, totalSent: number, totalExpected: number): void;
  taskDidReceiveBodyData?(task: JSURLSessionTask, totalReceived: number, totalExpected: number): void;
}

declare class JSURLSessionDataTask extends JSURLSessionTask{
  originalRequest: JSURLRequest;
  currentRequest: JSURLRequest;
  response: JSURLResponse | null;
}

declare class JSURLSessionStreamTask extends JSURLSessionTask{
  originalURL: JSURL;
  currentURL: JSURL;
  requestedProtocols: string[];
  protocol: string;
  sendMessage(data: JSData): void;
  streamDelegate: JSURLSessionStreamTaskDelegate;
}

declare interface JSURLSessionStreamTaskDelegate{
  taskDidOpenStream?(task: JSURLSessionStreamTask): void;
  taskDidCloseStream?(task: JSURLSessionStreamTask): void;
  taskDidReceiveStreamData?(task: JSURLSessionStreamTask, data: JSData): void;
  taskDidReceiveStreamError?(task: JSURLSessionStreamTask): void;
}

declare class JSURLSessionUploadTask extends JSURLSessionDataTask{
}

declare class JSURLRequest extends JSObject{
  static initWithURL<T>(this: { new(): T }, url: JSURL): T;
  initWithURL(url: JSURL): this | void
  method: string;
  headerMap: JSMIMEHeaderMap;
  headers: JSMIMEHeader[];
  addBasicAuthorization(username: string, password: string): void;
  addBasicAuthorization(username: string): void;
  addBearerAuthorization(token: string): void;
  contentType: JSMediaType;
  data: JSData;
  object: object;
  form: JSFormFieldMap;
  response: JSURLResponse | null;
}
declare namespace JSURLRequest{
  enum Method{
    get,
    post,
    put,
    delete,
  }
}

declare class JSURLResponse extends JSObject{
  statusCode: number;
  statusClass: number;
  statusText: string;
  assertSuccess(): void;
  headerMap: JSMIMEHeaderMap;
  headers: JSMIMEHeader[];
  contentType: JSMediaType | null;
  contentLength: number | null;
  data: JSData | null;
  object: object | null;
}
declare namespace JSURLResponse{
  enum StatusCode{
    unknown,
    noResponse,
    continue,
    switchingProtocols,
    ok,
    created,
    accepted,
    nonAuthorativeInformation,
    noContent,
    resetContent,
    partialContent,
    multipleChoices,
    movedPermanently,
    found,
    seeOther,
    notModified,
    useProxy,
    temporaryRedirect,
    badRequest,
    unauthorized,
    paymentRequired,
    forbidden,
    notFound,
    methodNotAllowed,
    notAcceptable,
    proxyAuthenticationRequired,
    requestTimeout,
    conflict,
    gone,
    lengthRequired,
    preconditionFailed,
    payloadTooLarge,
    uriTooLong,
    unsupportedMediaType,
    rangeNotSatisfiable,
    expectationFailed,
    upgradeRequired,
    preconditionRequired,
    tooManyRequests,
    requestHeaderFieldsTooLarge,
    unavailableForLegalReasons,
    internalServerError,
    notImplemented,
    badGateway,
    serviceUnavailable,
    gatewayTimeout,
    httpVersionNotSupported,
  }
  enum StatusClass{
    unknown,
    noResponse,
    informational,
    success,
    redirect,
    clientError,
    serverError,
  }
}

declare class JSURLResponseError extends Error{
  response: JSURLResponse;
}

declare class JSFormFieldMap{
  constructor();
  constructor(map: JSFormFieldMap);
  decode(urlEncodedData: string, decodeSpaceAsPlus?: boolean): void;
  encode(reserved: {}, encodeSpaceAsPlus?: boolean): JSData;
  urlEncoded(): JSData;
  get(name: string): string;
  get(name: string, defaultValue: string): string;
  getAll(name: string): string[];
  add(name: string, value: string): void;
  set(name: string, value: string): void;
  unset(name: string): void;
}
declare function JSFormFieldMap(): JSFormFieldMap;
declare function JSFormFieldMap(map: JSFormFieldMap): JSFormFieldMap;


declare class JSFormField{
  constructor(name: string, value: string);
  constructor(name: string);
  constructor(field: JSFormField);
  name: string;
  value: string;
}
declare function JSFormField(name: string, value: string): JSFormField;
declare function JSFormField(name: string): JSFormField;
declare function JSFormField(field: JSFormField): JSFormField;


declare class JSMediaType{
  constructor(string: string);
  constructor(string: string, parameters: {});
  constructor(mediaType: JSMediaType);
  mime: string;
  type: string;
  subtype: string;
  parameters: {};
}
declare function JSMediaType(string: string): JSMediaType;
declare function JSMediaType(string: string, parameters: {}): JSMediaType;
declare function JSMediaType(mediaType: JSMediaType): JSMediaType;


declare class JSMIMEHeader{
  constructor(name: string, value: string);
  constructor(header: JSMIMEHeader);
  name: string;
  lowerName: string;
  value: string;
}
declare function JSMIMEHeader(name: string, value: string): JSMIMEHeader;
declare function JSMIMEHeader(header: JSMIMEHeader): JSMIMEHeader;


declare class JSMIMEHeaderMap{
  constructor();
  constructor(map: JSMIMEHeaderMap);
  parse(headers: string): void;
  get(name: string): string;
  get(name: string, defaultValue: string): string;
  getAll(name: string): string[];
  add(name: string, value: string): void;
  set(name: string, value: string): void;
  unset(name: string): void;
}
declare function JSMIMEHeaderMap(): JSMIMEHeaderMap;
declare function JSMIMEHeaderMap(map: JSMIMEHeaderMap): JSMIMEHeaderMap;


declare class JSSynchronizer extends JSObject{
  static initWithAction<T>(this: { new(): T }, action: (syncContext: JSSynchronizer.Context) => void, target?: object): T;
  initWithAction(action: (syncContext: JSSynchronizer.Context) => void, target?: object): this | void
  static initWithAction<T>(this: { new(): T }, action: () => Promise<void>, target?: object): T;
  initWithAction(action: () => Promise<void>, target?: object): this | void
  state: JSSynchronizer.State;
  error: Error | null;
  pendingInterval: number;
  successInterval: number;
  sync(): void;
  syncImmediately(): void;
  cancel(): void;
}
declare namespace JSSynchronizer{
  type Context = {
    started(): void;
    completed(): void;
    completed(error: Error): void;
  };
  enum State{
    idle,
    pending,
    working,
    success,
    error,
  }
}

declare class JSIPAddress extends JSObject{
  static initWithString<T>(this: { new(): T }, string: string | null): T | null;
  initWithString(string: string | null): this | void | null
  family: JSIPAddress.Family;
  data: JSData;
  stringRepresentation(): string;
  isEqual(other: JSIPAddress): boolean;
}
declare namespace JSIPAddress{
  enum Family{
    ip4,
    ip6,
  }
}

declare class JSFont{
  static initWithDescriptor<T>(this: { new(): T }, descriptor: JSFontDescriptor, pointSize: number): T;
  initWithDescriptor(descriptor: JSFontDescriptor, pointSize: number): this | void
  static fontWithFamily(family: string, pointSize: number, weight: JSFont.Weight, style: JSFont.Style): void;
  static systemFontOfSize(pointSize: number): void;
  descriptor: JSFontDescriptor;
  fullName: string;
  postScriptName: string;
  familyName: string;
  faceName: string;
  pointSize: number;
  ascender: number;
  descender: number;
  lineHeight: number;
  leading: number;
  fontWithPointSize(pointSize: number): JSFont;
  fontWithWeight(weight: JSFont.Weight): JSFont;
  fontWithStyle(style: JSFont.Style): JSFont;
  glyphsForString(string: string): number[];
  glyphForCharacter(character: UnicodeChar): number;
  characterForGlyph(glyph: number): UnicodeChar;
  charactersForGlyphs(glyphs: number[]): UnicodeChar[];
  stringForGlyphs(glyphs: number[]): string;
  widthOfGlyph(glyph: number): number;
  widthOfCharacter(character: UnicodeChar): number;
  widthOfString(string: string): number;
}
declare namespace JSFont{
  enum Size{
    normal,
    detail,
    heading,
  }
  enum Weight{
    ultraLight,
    thin,
    light,
    regular,
    medium,
    semibold,
    bold,
    heavy,
    black,
  }
  enum Style{
    normal,
    italic,
  }
}

declare class JSFontDescriptor{
  name: string;
  postScriptName: string;
  family: string;
  face: string;
  weight: JSFont.Weight;
  style: JSFont.Style;
  ascender: number;
  descender: number;
  unitsPerEM: number;
  descriptorWithWeight(weight: JSFont.Weight): JSFontDescriptor;
  descriptorWithStyle(style: JSFont.Style): JSFontDescriptor;
  glyphForCharacter(character: UnicodeChar): number;
  characterForGlyph(glyph: number): UnicodeChar;
  charactersForGlyphs(glyphs: number[]): UnicodeChar[];
  stringForGlyphs(glyphs: number[]): string;
  widthOfGlyph(glyph: number): number;
  widthOfCharacter(character: UnicodeChar): number;
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
}

declare class JSTextFrame extends JSObject{
  drawInContextAtPoint(context: JSContext, point: JSPoint): void;
  size: JSSize;
  usedSize: JSSize;
  range: JSRange;
  lines: JSTextLine[];
  lineForCharacterAtIndex(index: number): JSTextLine | null;
  lineAtPoint(point: JSPoint): JSTextLine | null;
  rectForLine(line: JSTextLine): JSRect;
}

declare class JSTextFramesetter extends JSObject{
  attributedString: JSAttributedString;
  defaultParagraphStyle: JSParagraphStyle;
  createFrame(size: JSSize, range: JSRange, maximumLines: number): JSTextFrame;
  attributes: object;
}

declare class JSTextLine extends JSObject{
  drawInContextAtPoint(context: JSContext, point: JSPoint): void;
  origin: JSPoint;
  size: JSSize;
  baseline: number;
  range: JSRange;
  runs: JSTextRun[];
  runForCharacterAtIndex(index: number): JSTextRun | null;
  runAtPoint(point: JSPoint): JSTextLine | null;
  truncatedLine(width: number, token?: string): JSTextLine;
}

declare class JSTextRun extends JSObject{
  drawInContextAtPoint(context: JSContext, point: JSPoint): void;
  origin: JSPoint;
  size: JSSize;
  baseline: number;
  range: JSRange;
  glyphs: number[];
  font: JSFont;
  attributes: {};
}

declare class JSTextStorage extends JSAttributedString{
  layoutManagers: JSTextLayoutManager[];
  addLayoutManager(layoutManager: JSTextLayoutManager): void;
  removeLayoutManagerAtIndex(index: number): void;
  removeAllLayoutManagers(): void;
}

declare class JSTextTypesetter extends JSObject{
  attributedString: JSAttributedString;
  createLine(range: JSRange): JSTextLine;
  suggestLineBreak(width: number, range: JSRange, lineBreakMode: JSLineBreakMode): JSRange;
}

declare class JSParagraphStyle extends JSObject{
  minimumLineHeight: number;
  lineSpacing: number;
  textAlignment: JSTextAlignment;
  lineBreakMode: JSLineBreakMode;
  lineHeightMultiple: void;
  paragraphSpacing: void;
  firstLineHeadIndent: void;
  headIndent: void;
  tailIndent: void;
  styleWithAttributes(attributes: {}): JSParagraphStyle;
}

declare class JSTextAttachment extends JSObject{
  static initWithImage<T>(this: { new(): T }, image: JSImage, size: JSSize | null): T;
  initWithImage(image: JSImage, size: JSSize | null): this | void
  static initWithImageName<T>(this: { new(): T }, imageName: string, size: JSSize | null): T;
  initWithImageName(imageName: string, size: JSSize | null): this | void
  static initWithImageForFont<T>(this: { new(): T }, imageName: string, font: JSFont): T;
  initWithImageForFont(imageName: string, font: JSFont): this | void
}

declare class JSTextLayoutManager extends JSObject{
  textStorage: JSTextStorage;
  defaultFont: JSFont | null;
  defaultTextColor: JSColor;
  defaultParagraphStyle: JSParagraphStyle;
  addTextContainer(textContainer: JSTextContainer): void;
  insertTextContainerAtIndex(textContainer: JSTextContainer, index: number): void;
  removeTextContainerAtIndex(index: number): void;
  setNeedsLayout(): void;
  layoutIfNeeded(): void;
  drawContainerInContextAtPoint(context: JSContext, point: JSPoint): void;
  delegate: JSTextLayoutManagerDelegate | null;
}

declare interface JSTextLayoutManagerDelegate{
  layoutManagerDidInvalidateLayout?(layoutManager: JSTextLayoutManager): void;
  layoutManagerDidCompleteLayoutForContainer?(layoutManager: JSTextLayoutManager, container: JSTextContainer, isAtEnd: boolean): void;
  layoutManagerTextContainerForLocation?(layoutManager: JSTextLayoutManager, location: JSPoint): void;
}

declare class JSTextContainer extends JSObject{
  static initWithSize<T>(this: { new(): T }, size: JSSize): T;
  initWithSize(size: JSSize): this | void
  size: JSSize;
}

declare enum JSTextAlignment{
  left,
  center,
  right,
}

declare enum JSLineBreakMode{
  truncateTail,
  wordWrap,
  characterWrap,
}

declare function JSMD5Hash(data: JSData): JSData;

declare class JSMD5Hash{
  constructor();
  add(data: JSData): void;
  finish(): void;
  digest(): JSData;
}
declare function JSMD5Hash(): JSMD5Hash;


declare function JSSHA1Hash(data: JSData): JSData;

declare class JSSHA1Hash{
  constructor();
  add(data: JSData): void;
  finish(): void;
  digest(): JSData;
}
declare function JSSHA1Hash(): JSSHA1Hash;


declare var JSGlobalObject: object;

declare class JSTimer extends JSObject{
  static scheduledTimerWithInterval(interval: number, action: (() => void), target?: object): JSTimer;
  static scheduledRepeatingTimerWithInterval(interval: number, action: (() => void), target?: object): JSTimer;
  static initWithInterval<T>(this: { new(): T }, interval: number, repeats: boolean, action: (() => void), target?: object): T;
  initWithInterval(interval: number, repeats: boolean, action: (() => void), target?: object): this | void
  schedule(): void;
  invalidate(): void;
  static waitInterval(interval: number): void;
}

declare class JSNumberFormatter extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  static initWithLocale<T>(this: { new(): T }, locale: JSLocale): T;
  initWithLocale(locale: JSLocale): this | void
  locale: JSLocale;
  format: string;
  style: JSNumberFormatter.Style;
  positiveFormat: string;
  negativeFormat: string;
  stringFromNumber(number: number): void;
  numberFromString(string: string): void;
  positivePrefix: string;
  positiveSuffix: number;
  negativePrefix: string;
  negativeSuffix: number;
  usesGroupingSeparator: boolean;
  groupingSeparator: string;
  groupingSize: number;
  secondaryGroupingSize: number;
  multiplier: number;
  percentSymbol: string;
  perMilleSymbol: string;
  minusSign: string;
  plusSign: string;
  zeroSymbol: string;
  notANumberSymbol: string;
  nullSymbol: string;
  positiveInfinitySymbol: string;
  negativeInfinitySymbol: string;
  currencySymbol: string;
  currencyCode: string;
}
declare namespace JSNumberFormatter{
  enum Style{
    none,
    decimal,
    percent,
    currency,
    currencyAccounting,
    currencyISOCode,
  }
}

declare class JSXMLParser extends JSObject{
  static initWithString<T>(this: { new(): T }, xmlString: string): T;
  initWithString(xmlString: string): this | void
  static initWithData<T>(this: { new(): T }, xmlData: JSData, encoding?: String.Encoding): T;
  initWithData(xmlData: JSData, encoding?: String.Encoding): this | void
  delegate: JSXMLParserDelegate;
  parse(): void;
  stop(): void;
  mode: JSXMLParser.Mode;
  xml: string;
}
declare namespace JSXMLParser{
  enum Mode{
    xml,
    html,
  }
}

declare interface JSXMLParserDelegate{
  xmlParserDidBeginDocument?(parser: JSXMLParser): void;
  xmlParserFoundDocumentType?(parser: JSXMLParser, name: string, publicID: string | null, systemID: string | null): void;
  xmlParserFoundProcessingInstruction?(parser: JSXMLParser, name: string, data: string): void;
  xmlParserFoundComment?(parser: JSXMLParser, text: string): void;
  xmlParserDidEndDocument?(parser: JSXMLParser): void;
  xmlParserDidBeginElement?(parser: JSXMLParser, name: string, prefix: string | null, namespace: string | null, attributes: JSXMLAttributeMap): void;
  xmlParserDidEndElement?(parser: JSXMLParser, name: string, prefix: string | null, namespace: string | null): void;
  xmlParserFoundText?(parser: JSXMLParser, text: string): void;
  xmlParserFoundCDATA?(parser: JSXMLParser, text: string): void;
  xmlParserErrorOccurred?(parser: JSXMLParser, error: Error): void;
}

declare class JSXMLAttributeMap{
  contains(name: string, namespace?: string | null): boolean;
  get(name: string, namespace?: string | null): string | null;
  all(): JSXMLAttributeMap.Attribute[];
}
declare namespace JSXMLAttributeMap{
  type Attribute = {
    name: string;
    prefix: string | null;
    namespace: string | null;
    value: string | null;
  };
}

declare function UUID(): string;

declare function JSCopy<T>(obj: Array<T>): Array<T>;
declare function JSCopy<T extends {[k: string]: any}>(obj: T): T;

declare function JSDeepCopy<T>(obj: Array<T>): Array<T>;
declare function JSDeepCopy<T extends {[k: string]: any}>(obj: T): T;
