// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class IKBitmap extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData, size: JSSize): T;
  initWithData(data: JSData, size: JSSize): this | void
  static initWithEncodedData<T>(this: { new(): T }, encodedData: JSData): T | null;
  initWithEncodedData(encodedData: JSData): this | void | null
  size: JSSize;
  data: JSData;
  encodedData(format: IKBitmap.Format): JSData;
}
declare namespace IKBitmap{
  enum Format{
    unknown,
    png,
    jpeg,
  }
}

declare class IKBitmapContext extends JSContext{
  static initWithSize<T>(this: { new(): T }, size: JSSize): T;
  initWithSize(size: JSSize): this | void
  image(format: IKBitmap.Format, completion: (image: JSImage | null) => void, target?: any): void;
  image(format: IKBitmap.Format): Promise<JSImage>;
  bitmap(completion: (bitmap: IKBitmap | null) => void, target?: any): void;
  bitmap(): Promise<IKBitmap>;
}

declare class IKDecoder extends JSObject{
  static initWithFormat<T>(this: { new(): T }, format: IKBitmap.Format, encodedData: JSData): T | null;
  initWithFormat(format: IKBitmap.Format, encodedData: JSData): this | void | null
  format: IKBitmap.Format;
  getBitmap(): IKBitmap | null;
}

declare class IKEncoder extends JSObject{
  static initWithFormat<T>(this: { new(): T }, format: IKBitmap.Format, bitmap: IKBitmap): T | null;
  initWithFormat(format: IKBitmap.Format, bitmap: IKBitmap): this | void | null
  format: IKBitmap.Format;
  getData(): JSData;
}
