// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./SecurityKit" />

declare class NKUserNotificationCenter extends JSObject{
  static shared: NKUserNotificationCenter;
  registerForRemoteNotifications(completion: (registration: NKUserNotificationCenter.RemoteNotificationsRegistration, error: Error | null) => void, target?: any): void;
  registerForRemoteNotifications(): Promise<NKUserNotificationCenter.RemoteNotificationsRegistration>;
  unregisterForRemoteNotifications(completion: (error: Error | null) => void, target?: any): void;
  unregisterForRemoteNotifications(): Promise<void>;
  webPushApplicationServerJWK: SECJSONWebToken.JSONWebKey | null;
  requestAuthorization(completion: (authorized: NKUserNotificationCenter.AuthorizationStatus) => void, target?: object): void;
  requestAuthorization(): Promise<NKUserNotificationCenter.AuthorizationStatus>;
  getAuthorizationStatus(completion: (status: NKUserNotificationCenter.AuthorizationStatus) => void, target?: object): void;
  getAuthorizationStatus(): Promise<NKUserNotificationCenter.AuthorizationStatus>;
  addNotification(notification: NKUserNotification, date?: JSDate | null): void;
  removeNotification(notification: NKUserNotification): void;
}
declare namespace NKUserNotificationCenter{
  enum RegistrationType{
    web,
  }
  type RemoteNotificationsRegistration = {
    type: NKUserNotificationCenter.RegistrationType;
    options: NKUserNotificationCenter.RemoteNotificationsRegistration.WebPushOptions;
    subscription: NKUserNotificationCenter.RemoteNotificationsRegistration.WebPushSubscription;
  };
  namespace RemoteNotificationsRegistration{
    type WebPushSubscription = {
      endpoint: string;
      expirationTime: number | null;
      keys: NKUserNotificationCenter.RemoteNotificationsRegistration.WebPushSubscription.WebPushSubscriptionKeys;
    };
    namespace WebPushSubscription{
      type WebPushSubscriptionKeys = {
        p256dh: string;
        auth: string;
      };
    }
    type WebPushOptions = {
      applicationServerJWK: SECJSONWebToken.JSONWebKey;
    };
  }
  enum AuthorizationStatus{
    unknown,
    authorized,
    denied,
  }
}

declare class NKUserNotification extends JSObject{
  static initWithTitle<T>(this: { new(): T }, title: string, body?: string | null): T;
  initWithTitle(title: string, body?: string | null): this | void
  identifier: string;
  title: string;
  body: string | null;
  priority: NKUserNotification.Priority;
  timeToLive: number;
}
declare namespace NKUserNotification{
  enum Priority{
    normal,
    veryLow,
    low,
    high,
  }
}
