// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class PDFReader extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData): T;
  initWithData(data: JSData): this | void
  static initWithStream<T>(this: { new(): T }, stream: PDFReaderStream): T;
  initWithStream(stream: PDFReaderStream): this | void
  open(completion: (status: PDFReader.Status, document: PDFDocument | null) => void, target?: object): void;
  open(): Promise<[PDFReader.Status, PDFDocument]>;
  authenticate(password: string, completion: (status: PDFReader.Status, document: PDFDocument | null) => void, target?: object): void;
  authenticate(password: string): Promise<[PDFReader.Status, PDFDocument]>;
}
declare namespace PDFReader{
  enum Status{
    open,
    error,
    passwordRequired,
    unsupportedVersion,
    unsupportedEncryption,
  }
}

declare class PDFReaderStream extends JSObject{
  byte(): number;
  byteBackwards(): number;
  seek(offset: number): void;
  getOffset(): number;
  getLength(): number;
}

declare class PDFReaderDataStream extends PDFReaderStream{
  static initWithData<T>(this: { new(): T }, data: JSData): T;
  initWithData(data: JSData): this | void
}

declare class PDFDocument extends PDFObject{
  pageCount: number;
  page(index: number): PDFPage;
}

declare class PDFPage extends PDFObject{
  getText(completion: (text: string) => void, target?: object): void;
  getText(): Promise<string>;
  getOperationIterator(completion: (iterator: PDFOperationIterator) => void, target?: object): void;
  getOperationIterator(): Promise<PDFOperationIterator>;
  getContentsData(completion: (data: JSData) => void, target?: object): void;
  getContentsData(): Promise<JSData>;
  bounds: JSRect;
  uncroppedBounds: JSRect;
  prepareDrawing(completion: (drawing: PDFDrawing) => void, target?: object): void;
  prepareDrawing(): Promise<PDFDrawing>;
}

declare class PDFOperationIterator extends JSObject{
  static initWithData<T>(this: { new(): T }, data: JSData): T;
  initWithData(data: JSData): this | void
  state: PDFGraphicsState;
  resources: PDFResources;
  next(): PDFStreamOperation | null;
  reset(): void;
}

declare class PDFStreamOperation{
  operator: PDFStreamOperation.Operator;
  operands: any[];
}
declare namespace PDFStreamOperation{
  enum Operator{
    pushState,
    popState,
    concatenateCTM,
    lineWidth,
    lineCap,
    lineJoin,
    miterLimit,
    dashPattern,
    renderingIntent,
    flatness,
    updateState,
    moveTo,
    lineTo,
    curveTo,
    curveToUsingCurrent,
    curveToUsingEnding,
    closeSubpath,
    rectangle,
    endPath,
    clip,
    clipEvenOdd,
    strokePath,
    closeStrokePath,
    fillPath,
    fillPathAlias,
    fillPathEvenOdd,
    fillStrokePath,
    fillStrokePathEvenOdd,
    closeFillStrokePath,
    closeFillStrokePathEvenOdd,
    strokeColorSpace,
    fillColorSpace,
    strokeColor,
    fillColor,
    strokeColorNamed,
    fillColorNamed,
    strokeColorGray,
    fillColorGray,
    strokeColorRGB,
    fillColorRGB,
    strokeColorCMYK,
    fillColorCMYK,
    shading,
    xobject,
    beginImage,
    beginImageData,
    endImage,
    characterSpacing,
    wordSpacing,
    textHorizontalScaling,
    textLeading,
    font,
    textRenderingMode,
    textRise,
    beginText,
    endText,
    textMatrix,
    nextLineManual,
    nextLineLeading,
    nextLine,
    nextLineText,
    text,
    textArray,
    xTextAdvance,
    fontGlyphWidthColor,
    fontGlyphWidth,
    beginCodeSpaceRange,
    endCodeSpaceRange,
    beginbfchar,
    endbfchar,
    beginbfrange,
    endbfrange,
    beginMarkedContentProperties,
    beginMarkedContent,
    endMarkedContent,
    defineMarkedContentPointProperties,
    defineMarkedContentPoint,
    beginFunction,
    endFunction,
    beginCompatibility,
    endCompatibility,
  }
}

declare class PDFGraphicsState{
  transform: JSAffineTransform;
  firstPoint: JSPoint | null;
  lastPoint: JSPoint | null;
  lineWidth: number;
  strokeColorSpace: PDFColorSpace;
  strokeColorComponents: number[];
  fillColorSpace: PDFColorSpace;
  fillColorComponents: number[];
  lineCap: PDFGraphicsState.LineCap;
  lineJoin: PDFGraphicsState.LineJoin;
  miterLimit: number;
  dashArray: number[];
  dashPhase: number;
  renderingIntent: string;
  strokeAdjustment: boolean;
  blendMode: string;
  softMask: void;
  strokeAlpha: number;
  fillAlpha: number;
  alphaSource: boolean;
  flatness: number;
  textTransform: JSAffineTransform | null;
  textLineTransform: JSAffineTransform | null;
  characterSpacing: number;
  wordSpacing: number;
  textHorizontalScaling: number;
  textLeading: number;
  font: PDFFont | null;
  fontSize: number;
  textRenderingMode: PDFGraphicsState.TextRenderingMode;
  textRise: number;
  textKnockout: number;
}
declare namespace PDFGraphicsState{
  enum LineCap{
    butt,
    round,
    square,
  }
  enum LineJoin{
    miter,
    round,
    square,
  }
  enum TextRenderingMode{
    fill,
    stroke,
    fillStroke,
    invisible,
    fillAddPath,
    strokeAddPath,
    fillStrokeAddPath,
    addPath,
  }
}

declare class PDFObject{
}

declare class PDFName{
  valueDecodingUTF8(): string;
}

declare class PDFResources extends PDFObject{
  font(name: PDFName): PDFFont | null;
  fonts(): PDFFont[];
  image(name: PDFName): PDFImage | null;
  colorSpace(name: PDFName): PDFColorSpace | null;
  form(name: PDFName): PDFForm | null;
  xObject(name: PDFName): PDFXObject | null;
  graphicsState(name: PDFName): PDFObject | null;
}

declare class PDFColorSpace{
  colorFromComponents(components: number[]): JSColor;
  numberOfComponents: number;
  defaultComponents(): number[];
}

declare class PDFFont extends PDFObject{
  foundationFontOfSize(pointSize: number): JSFont;
  stringFromData(data: JSData): string;
  fontCompatibleStringFromData(data: JSData): string;
  widthOfData(data: JSData, characterSpacing: number): number;
}

declare class PDFImage extends PDFXObject{
  foundationImage: JSImage;
}

declare class PDFForm extends PDFXObject{
  bounds: JSRect;
  transform: JSAffineTransform;
  drawing: PDFDrawing;
  getOperationIterator(completion: (iterator: PDFOperationIterator) => void, target?: object): void;
  getOperationIterator(): Promise<PDFOperationIterator>;
}

declare class PDFStream extends PDFObject{
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
}

declare class PDFXObject extends PDFStream{
}

declare class PDFDrawing extends JSObject{
  drawInContext(context: JSContext, rect: JSRect): void;
  backgroundColor: JSColor;
}

declare class PDFContext extends JSContext{
  static initWithURL<T>(this: { new(): T }, url: JSURL): T;
  initWithURL(url: JSURL): this | void
  static initWithURL<T>(this: { new(): T }, url: JSURL, mediaBox: JSRect): T;
  initWithURL(url: JSURL, mediaBox: JSRect): this | void
  beginPage(options?: PDFContext.PageOptions): void;
  endDocument(completion: (success: boolean) => void, target?: object): void;
  endDocument(): void;
}
declare namespace PDFContext{
  type PageOptions = {
    mediaBox: JSRect;
    usePDFCoordinates: boolean;
  };
}
