// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class QRCode{
  static initWithURL<T>(this: { new(): T }, url: JSURL): T | null;
  initWithURL(url: JSURL): this | void | null
  static initWithString<T>(this: { new(): T }, string: string, encoding?: String.Encoding): T | null;
  initWithString(string: string, encoding?: String.Encoding): this | void | null
  static initWithData<T>(this: { new(): T }, data: JSData): T | null;
  initWithData(data: JSData): this | void | null
  prepareDrawing(): QRCodeDrawing;
}

declare class QRCodeDrawing{
  size: number;
  quietSize: number;
  modules: JSData;
}
declare namespace QRCodeDrawing{
  class Flag{
    static on: number;
    static quiet: number;
    static finder: number;
    static alignment: number;
    static timing: number;
    static format: number;
    static version: number;
    static function: number;
    static reserved: number;
  }
}

interface JSContext{
  drawQRCode(qrCode: QRCode): void;
}
