// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class SECCipher extends JSObject{
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECCipher.Algorithm): T;
  initWithAlgorithm(algorithm: SECCipher.Algorithm): this | void
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECCipher.Algorithm, options: SECCipher.CipherOptions): T;
  initWithAlgorithm(algorithm: SECCipher.Algorithm, options: SECCipher.CipherOptions): this | void
  encrypt(data: JSData, key: SECKey, completion: (encrypted: JSData | null) => void, target?: object): void;
  encrypt(data: JSData, key: SECKey): Promise<JSData>;
  encryptString(string: string, key: SECKey, completion: (encrypted: JSData | null) => void, target?: object): void;
  encryptString(string: string, key: SECKey): Promise<JSData>;
  decrypt(data: JSData, key: SECKey, completion: (decrypted: JSData | null) => void, target?: object): void;
  decrypt(data: JSData, key: SECKey): Promise<JSData>;
  decryptString(encrypted: JSData, key: SECKey, completion: (decrypted: string | null) => void, target?: object): void;
  decryptString(encrypted: JSData, key: SECKey): Promise<string>;
  createKey(completion: (key: SECKey | null) => void, target?: object): void;
  createKey(): Promise<SECKey>;
  createKeyWithData(keyData: JSData, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyWithData(keyData: JSData): Promise<SECKey>;
  createKeyWithPassphrase(passphrase: string, salt: JSData, iterations: number, hash: SECHash.Algorithm, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyWithPassphrase(passphrase: string, salt: JSData, iterations: number, hash: SECHash.Algorithm): Promise<SECKey>;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey): Promise<SECKey>;
  createKeyFromKeystore(keystore: SECKeystore, identifier: string, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromKeystore(keystore: SECKeystore, identifier: string): Promise<SECKey>;
  wrapKey(key: SECKey, wrappingKey: SECKey, completion: (encrypted: JSData | null) => void, target?: object): void;
  wrapKey(key: SECKey, wrappingKey: SECKey): Promise<JSData>;
  unwrapKey(wrappedKeyData: JSData, unwrappedKeyAlgorithm: SECCipher.Algorithm, wrappingKey: SECKey, completion: (key: SECKey | null) => void, target?: object): void;
  unwrapKey(wrappedKeyData: JSData, unwrappedKeyAlgorithm: SECCipher.Algorithm, wrappingKey: SECKey): Promise<SECKey>;
  static getRandomData(length: number): JSData;
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECCipher.Algorithm, keyBitLength: number): T;
  initWithAlgorithm(algorithm: SECCipher.Algorithm, keyBitLength: number): this | void
}
declare namespace SECCipher{
  enum Algorithm{
    aesCipherBlockChaining,
    aesCBC,
    aesCounter,
    aesCTR,
    aesGaloisCounterMode,
    aesGCM,
    rsaOAEP,
    rivestCipher4,
    rc4,
  }
  type CipherOptions = {
    keyBitLength?: number | null;
    iv?: JSData | null;
    tagByteLength?: number | null;
    ivByteLength?: number | null;
    additionalData?: JSData | null;
    modulusLength?: number | null;
    publicExponent?: number | null;
    label?: JSData | null;
    hash?: SECHash.Algorithm | null;
  };
}

declare class SECKey extends JSObject{
  id: string | null;
  type: SECKey.KeyType;
  getJWK(completion: (data: SECJSONWebToken.JSONWebKey | null) => void, target?: object): void;
  getJWK(): Promise<SECJSONWebToken.JSONWebKey>;
  publicKey: SECKey | null;
  getData(completion: (data: JSData | null) => void, target?: object): void;
  getData(): Promise<JSData>;
}
declare namespace SECKey{
  enum KeyType{
    secret,
    private,
    public,
  }
}

declare type SECKeyPair = {
  public: SECKey;
  private: SECKey;
};

declare class SECHash extends JSObject{
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECHash.Algorithm): T;
  initWithAlgorithm(algorithm: SECHash.Algorithm): this | void
  update(data: JSData): void;
  digest(completion: (digest: JSData | null) => void, target?: object): void;
  digest(): Promise<JSData>;
}
declare namespace SECHash{
  enum Algorithm{
    sha1,
    sha256,
    sha384,
    sha512,
  }
}

declare class SECHMAC extends JSObject{
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECHMAC.Algorithm): T;
  initWithAlgorithm(algorithm: SECHMAC.Algorithm): this | void
  key: SECKey;
  createKey(completion: (key: SECKey | null) => void, target?: object): void;
  createKey(): Promise<SECKey>;
  createKeyWithData(keyData: JSData, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyWithData(keyData: JSData): Promise<SECKey>;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey): Promise<SECKey>;
  update(data: JSData): void;
  sign(completion: (signature: JSData | null) => void, target?: object): void;
  sign(): Promise<JSData>;
}
declare namespace SECHMAC{
  enum Algorithm{
    sha256,
    sha384,
    sha512,
  }
}

declare class SECSign extends JSObject{
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECSign.Algorithm): T;
  initWithAlgorithm(algorithm: SECSign.Algorithm): this | void
  static initFromJWK<T>(this: { new(): T }, jwk: SECJSONWebToken.JSONWebKey): T;
  initFromJWK(jwk: SECJSONWebToken.JSONWebKey): this | void
  createKeyPair(options: {}, completion: (key: SECKeyPair | null) => void, target?: object): void;
  createKeyPair(options: {}): Promise<SECKeyPair>;
  createJWKPair(options: {}, completion: (key: JWKKeyPair | null) => void, target?: object): void;
  createJWKPair(options: {}): Promise<JWKKeyPair>;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey): Promise<SECKey>;
  createKeyFromKeystore(keystore: SECKeystore, identifier: string, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromKeystore(keystore: SECKeystore, identifier: string): Promise<SECKey>;
  update(data: JSData): void;
  sign(key: SECKey, completion: (signature: JSData) => void, target?: object): void;
  sign(key: SECKey): Promise<JSData>;
}
declare namespace SECSign{
  enum Algorithm{
    rsaSHA256,
    rsaSHA384,
    rsaSHA512,
    ellipticCurveSHA26,
    ellipticCurveSHA384,
    ellipticCurveSHA512,
  }
  type RSAOptions = {
    modulusLength: number;
    publicExponent: number;
  };
  type EllipticCurveOptions = {
    namedCurve: SECSign.EllipticCurve;
  };
  enum EllipticCurve{
    p256,
    p384,
    p521,
  }
}

declare type JWKKeyPair = {
  public: SECJSONWebToken.JSONWebKey;
  private: SECJSONWebToken.JSONWebKey;
};

declare class SECVerify extends JSObject{
  static initWithAlgorithm<T>(this: { new(): T }, algorithm: SECVerify.Algorithm): T;
  initWithAlgorithm(algorithm: SECVerify.Algorithm): this | void
  static initFromJWK<T>(this: { new(): T }, jwk: SECJSONWebToken.JSONWebKey): T;
  initFromJWK(jwk: SECJSONWebToken.JSONWebKey): this | void
  update(data: JSData): void;
  verify(key: SECKey, signature: JSData, completion: (verified: boolean) => void, target?: object): void;
  verify(key: SECKey, signature: JSData): Promise<boolean>;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey, completion: (key: SECKey | null) => void, target?: object): void;
  createKeyFromJWK(jwk: SECJSONWebToken.JSONWebKey): Promise<SECKey>;
}
declare namespace SECVerify{
  enum Algorithm{
    rsaSHA256,
    rsaSHA384,
    rsaSHA512,
    ellipticCurveSHA26,
    ellipticCurveSHA384,
    ellipticCurveSHA512,
  }
}

declare class SECKeystore extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  addDataForIdentifier(data: JSData, identifier: string): void;
  addBase64URLForIdentifier(base64URL: string, identifier: string): void;
  addJWK(jwk: SECJSONWebToken.JSONWebKey): void;
  dataForIdentifier(identifier: string): JSData | null;
  jwkForIdentifier(identifier: string): SECJSONWebToken.JSONWebKey | null;
}

declare class SECKeychain extends JSObject{
  static initWithIdentifier<T>(this: { new(): T }, identifier: string): T;
  initWithIdentifier(identifier: string): this | void
  initializeWithMasterPassword(masterPassword: string, completion: (success: boolean) => void, target?: object): void;
  initializeWithMasterPassword(masterPassword: string): Promise<void>;
  static device: SECKeychain;
  locked: boolean;
  unlock(masterPassword: string, completion: (success: boolean) => void, target?: object): void;
  unlock(masterPassword: string): Promise<void>;
  lock(): void;
  close(completion: (success: boolean) => void, target?: object): void;
  close(): Promise<void>;
  add(item: {}, completion: (id: string | null) => void, target?: object): void;
  add(item: {}): Promise<string>;
  update(item: {}, completion: (id: string | null) => void, target?: object): void;
  update(item: {}): Promise<string>;
  remove(itemID: string, completion: (success: boolean) => void, target?: object): void;
  remove(itemID: string): Promise<void>;
  contains(itemID: string): boolean;
  get(itemID: string, completion: (item: {}) => void, target?: object): void;
  get(itemID: string): Promise<{}>;
  changeMasterPassword(oldPassword: string, newPassword: string, completion: (success: boolean) => void, target?: object): void;
  changeMasterPassword(oldPassword: string, newPassword: string): Promise<void>;
}

declare class SECPassword extends JSObject{
  static createWithPlainPassword(plainPassword: string, length: number, iterations: number, hash: SECHash.Algorithm, completion: (password: SECPassword) => void, target?: any): void;
  static createWithPlainPassword(plainPassword: string, length: number, iterations: number, hash: SECHash.Algorithm): Promise<void>;
  static initWithPBKDF2Data<T>(this: { new(): T }, pbkdf2Data: JSData, salt: JSData, iterations: number, hash: SECHash.Algorithm): T;
  initWithPBKDF2Data(pbkdf2Data: JSData, salt: JSData, iterations: number, hash: SECHash.Algorithm): this | void
  static initWithDictionary<T>(this: { new(): T }, dictionary: object): T;
  initWithDictionary(dictionary: object): this | void
  verify(plainPassword: string, completion: (verified: boolean) => void, target?: any): void;
  verify(plainPassword: string): Promise<void>;
  pbkdf2Data: JSData;
  salt: JSData;
  iterations: number;
  hash: SECHash.Algorithm;
  dictionaryRepresentation(): {};
}

declare class SECJSONWebAlgorithms extends JSObject{
}
declare namespace SECJSONWebAlgorithms{
  enum Algorithm{
    none,
    hmacSHA256,
    hmacSHA384,
    hmacSHA512,
    rsaSHA256,
    rsaSHA384,
    rsaSHA512,
    ellipticCurveSHA256,
    ellipticCurveSHA384,
    ellipticCurveSHA512,
    direct,
    rsaOAEP,
    ecdhES,
    aesGCM128,
    aesGCM192,
    aesGCM256,
    aesCBC128HS256,
    aesCBC192HS384,
    aesCBC256HS512,
  }
  enum KeyType{
    symmetric,
    rsa,
    ellipticCurve,
  }
  enum EllipticCurve{
    p256,
    p384,
    p521,
  }
}

declare class SECJSONWebToken extends JSObject{
  static initWithString<T>(this: { new(): T }, string: string | null): T | null;
  initWithString(string: string | null): this | void | null
  static initWithPayload<T>(this: { new(): T }, payload: object): T;
  initWithPayload(payload: object): this | void
  signed: boolean;
  verifiedPayload(publicKeys: SECJSONWebToken.JSONWebKey[], completion: (payload: {} | null) => void, target?: object): void;
  verifiedPayload(publicKeys: SECJSONWebToken.JSONWebKey[]): Promise<{}>;
  verifiedPayload(key: SECJSONWebToken.JSONWebKey, completion: (payload: {} | null) => void, target?: object): void;
  verifiedPayload(key: SECJSONWebToken.JSONWebKey): Promise<{}>;
  sign(key: SECJSONWebToken.JSONWebKey, completion: (jwt: string) => void, target?: any): void;
  sign(key: SECJSONWebToken.JSONWebKey): Promise<string>;
  stringRepresentation(): void;
  verifiedPayload(sharedSecretKeyData: JSData, completion: (payload: {} | null) => void, target?: object): void;
  verifiedPayload(sharedSecretKeyData: JSData): Promise<{}>;
}
declare namespace SECJSONWebToken{
  type JSONWebKey = {
  };
  enum Algorithm{
    none,
    hmacSHA256,
    hmacSHA384,
    hmacSHA512,
    rsaSHA256,
    rsaSHA384,
    rsaSHA512,
    ellipticCurveSHA256,
    ellipticCurveSHA384,
    ellipticCurveSHA512,
  }
  enum KeyType{
    symmetric,
    rsa,
    ellipticCurve,
  }
  enum EllipticCurve{
    p256,
    p384,
    p521,
  }
}

declare class SECJSONWebEncryption extends JSObject{
  static initWithString<T>(this: { new(): T }, string: string | null): T | null;
  initWithString(string: string | null): this | void | null
  static init<T>(this: { new(): T }): T;
  init(): this | void
  decrypt(privateKeys: SECJSONWebToken.JSONWebKey[], completion: (plaintext: JSData | null) => void, target?: object): void;
  decrypt(privateKeys: SECJSONWebToken.JSONWebKey[]): Promise<JSData>;
  decrypt(key: SECJSONWebToken.JSONWebKey, completion: (plaintext: JSData | null) => void, target?: object): void;
  decrypt(key: SECJSONWebToken.JSONWebKey): Promise<{}>;
  encrypt(plaintext: JSData, key: SECJSONWebToken.JSONWebKey, completion: (jwe: string) => void, target?: any): void;
  encrypt(plaintext: JSData, key: SECJSONWebToken.JSONWebKey): Promise<string>;
  stringRepresentation(): void;
}
declare namespace SECJSONWebEncryption{
  enum Algorithm{
    direct,
    rsaOAEP,
    ecdhES,
    aesGCM128,
    aesGCM192,
    aesGCM256,
    aesCBC128HS256,
    aesCBC192HS384,
    aesCBC256HS512,
  }
  enum KeyType{
    symmetric,
    rsa,
    ellipticCurve,
  }
  enum EllipticCurve{
    p256,
    p384,
    p521,
  }
}

declare class SECOneTimePassword extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  static initWithNumberOfDigits<T>(this: { new(): T }, numberOfDigits: number, timePeriod?: number, startDate?: JSDate): T;
  initWithNumberOfDigits(numberOfDigits: number, timePeriod?: number, startDate?: JSDate): this | void
  static initWithSecret<T>(this: { new(): T }, secret: JSData, numberOfDigits?: number, timePeriod?: number, startDate?: JSDate): T;
  initWithSecret(secret: JSData, numberOfDigits?: number, timePeriod?: number, startDate?: JSDate): this | void
  static initWithDictionary<T>(this: { new(): T }, dictionary: SECOneTimePassword.DictionaryRepresentation): T;
  initWithDictionary(dictionary: SECOneTimePassword.DictionaryRepresentation): this | void
  generateToken(completion: (token: string | null) => void, target?: object): void;
  generateToken(): Promise<string>;
  generateTokenForDate(date: JSDate, completion: (token: string | null) => void, target?: object): void;
  generateTokenForDate(date: JSDate): Promise<string>;
  secretData: JSData;
  numberOfDigits: number;
  timePeriod: number;
  startDate: JSDate;
  dictionaryRepresentation(): SECOneTimePassword.DictionaryRepresentation;
  urlForUsername(username: string, domain: string): JSURL;
}
declare namespace SECOneTimePassword{
  type DictionaryRepresentation = {
    secret?: string | null;
    digits?: number | null;
    period?: number | null;
    start?: number | null;
  };
}

declare class SECDeviceAuthentication extends JSObject{
  static shared: SECDeviceAuthentication;
  createPublicKey(registration: SECDeviceAuthentication.PublicKeyRegistration, completion: (result: SECDeviceAuthentication.RegistrationResult | null) => void, target?: any): void;
  createPublicKey(registration: SECDeviceAuthentication.PublicKeyRegistration): Promise<SECDeviceAuthentication.RegistrationResult>;
  authenticate(request: SECDeviceAuthentication.PublicKeyAuthentication, completion: (result: SECDeviceAuthentication.AuthenticationResult | null) => void, target?: any): void;
  authenticate(request: SECDeviceAuthentication.PublicKeyAuthentication): Promise<SECDeviceAuthentication.AuthenticationResult>;
  hasPlatformAuthenticator(completion: (hasAuthenticator: boolean) => void, target?: object): void;
  hasPlatformAuthenticator(): Promise<boolean>;
}
declare namespace SECDeviceAuthentication{
  type PublicKeyRegistration = {
    providerName: string | null;
    challengeData: JSData | null;
    supportedAlgorithms: SECSign.Algorithm[] | null;
    userId: string | null;
    accountName: string | null;
    domain: string | null;
    platform: boolean | null;
  };
  type RegistrationResult = {
    name: string;
    jwk: SECJSONWebToken.JSONWebKey;
    challenge: JSData;
    webauthn: SECDeviceAuthentication.RegistrationWebAuthn | null;
  };
  type RegistrationWebAuthn = {
    id: string;
    rawId: string;
    authenticatorAttachment: string;
    type: string;
    response: SECDeviceAuthentication.RegistrationWebAuthn.AttestationResponse;
  };
  namespace RegistrationWebAuthn{
    type AttestationResponse = {
      clientDataJSON: string;
      authenticatorData: string;
      attestationObject: string;
    };
  }
  type PublicKeyAuthentication = {
    challengeData: JSData;
    domain: string | null;
    allowedKeyIDs: string[] | null;
    platform: boolean | null;
  };
  type AuthenticationResult = {
    kid: string;
    challenge: JSData;
    signature: JSData;
    webauthn: SECDeviceAuthentication.SignatureWebAuthn | null;
  };
  type SignatureWebAuthn = {
    id: string;
    rawId: string;
    authenticatorAttachment: string;
    type: string;
    response: SECDeviceAuthentication.SignatureWebAuthn.AuthenticationResponse;
  };
  namespace SignatureWebAuthn{
    type AuthenticationResponse = {
      clientDataJSON: string;
      authenticatorData: string;
      signature: string;
    };
  }
}
