// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class SKApplication extends JSObject{
  shared: SKApplication;
  delegate: SKApplicationDelegate;
  environment: JSEnvironment;
  workingDirectoryURL: JSURL;
  secrets: SKSecrets;
}
declare namespace SKApplication{
  enum Signal{
    hangup,
    interrupt,
    terminate,
    SIGHUP,
    SIGINT,
    SIGTERM,
  }
}

declare interface SKApplicationDelegate{
  applicationDidFinishLaunching(application: SKApplication, launchOptions: JSArguments): void;
  applicationWillTerminate?(application: SKApplication, signal: SKApplication.Signal, completion: () => void): void;
  applicationWillTerminate?(application: SKApplication, signal: SKApplication.Signal): Promise<void>;
  applicationDidCrash?(application: SKApplication, error: Error, logs: JSLogRecord[]): void;
}

declare class SKHTTPServer extends JSObject{
  static initWithPort<T>(this: { new(): T }): T;
  initWithPort(): this | void
  rootRoute: SKHTTPRoute;
  healthCheckPath: string;
  delegate: SKHTTPServerDelegate | null;
  port: number;
  run(): void;
  stop(completion: () => void, target?: object): void;
  stop(): Promise<void>;
  defaultMaximumRequestContentLength: number;
  strictTransportSecurityEnabled: boolean;
}

declare interface SKHTTPServerDelegate{
  serverDidCreateContextForRequest?(server: SKHTTPServer, context: SKHTTPResponderContext, request: SKHTTPRequest): void;
  serverFoundResponder?(server: SKHTTPServer, responder: SKHTTPResponder): void;
  serverDidReceiveRequest?(server: SKHTTPServer, request: SKHTTPRequest): void;
  serverDidRespondToRequest?(server: SKHTTPServer, request: SKHTTPRequest): void;
}

declare class SKHTTPRoute extends JSObject{
  static initWithComponentStrings<T>(this: { new(): T }, componentStrings: string[], responderClass: JSClass): T;
  initWithComponentStrings(componentStrings: string[], responderClass: JSClass): this | void
  static FromMap(routeMap: {}, bundle?: JSBundle): SKHTTPRoute;
  parent: SKHTTPRoute | null;
  children: SKHTTPRoute[];
  addChild(child: SKHTTPRoute): void;
  contextWithMatches(matches: {}): SKHTTPResponderContext;
  responderWithRequest(request: SKHTTPRequest): SKHTTPResponder;
  pathComponentsForResponder(responderClass: JSClass, params: {}): string[];
  pathComponentsForParams(params: {}): string[];
}

declare class SKHTTPRequest extends JSObject{
  url: JSURL;
  method: string;
  headerMap: JSMIMEHeaderMap;
  origin: string | null;
  clientIPAddress: JSIPAddress;
  tag: string;
  receivedAt: JSDate;
  userAgent: SKUserAgent;
  contentType: JSMediaType | null;
  contentLength: number | null;
  maximumContentLength: number;
  getValidObject(validatingContructionClass: JSClass, completion: (error: SKValidatingObject.Error | null, valid: JSObject) => void, target?: object): void;
  getValidObject(validatingContructionClass: JSClass): Promise<SKValidatingObject>;
  getValidForm(validatingContructionClass: JSClass, completion: (error: SKValidatingObject.Error | null, valid: JSObject) => void, target?: object): void;
  getValidForm(validatingContructionClass: JSClass): Promise<SKValidatingObject>;
  getValidatingObject(completion: (validator: SKValidatingObject) => void, target?: object): void;
  getValidatingObject(): Promise<SKValidatingObject>;
  getValidatingForm(completion: (validator: SKValidatingObject) => void, target?: object): void;
  getValidatingForm(): Promise<SKValidatingObject>;
  getObject(completion: (obj: object) => void, target?: object): void;
  getObject(): Promise<object>;
  getForm(completion: (form: JSFormFieldMap) => void, target?: object): void;
  getForm(): Promise<JSFormFieldMap>;
  getData(completion: (data: JSData) => void, target?: object): void;
  getData(): Promise<JSData>;
  getValidQuery(validatingContructionClass: JSClass): void;
  getValidatingQuery(): void;
  bearerToken: string | null;
  username: string | null;
  password: string | null;
  response: SKHTTPResponse;
  close(): void;
  needsEntity(lastModified: JSDate, etag: string): void;
}

declare class SKHTTPResponse extends JSObject{
  statusCode: SKHTTPResponse.StatusCode;
  headerMap: JSMIMEHeaderMap;
  contentType: string;
  conentLength: number;
  writeString(string: string): void;
  writeData(data: JSData): void;
  writeFile(path: string): void;
  writeHeaderIfNeeded(): void;
  etag: string;
  lastModified: JSDate;
  setHeader(name: string, value: string): void;
  getHeader(name: string): string;
}
declare namespace SKHTTPResponse{
  enum StatusCode{
    unknown,
    noResponse,
    continue,
    switchingProtocols,
    ok,
    created,
    accepted,
    nonAuthorativeInformation,
    noContent,
    resetContent,
    partialContent,
    multipleChoices,
    movedPermanently,
    found,
    seeOther,
    notModified,
    useProxy,
    temporaryRedirect,
    badRequest,
    unauthorized,
    paymentRequired,
    forbidden,
    notFound,
    methodNotAllowed,
    notAcceptable,
    proxyAuthenticationRequired,
    requestTimeout,
    conflict,
    gone,
    lengthRequired,
    preconditionFailed,
    payloadTooLarge,
    uriTooLong,
    unsupportedMediaType,
    rangeNotSatisfiable,
    expectationFailed,
    upgradeRequired,
    preconditionRequired,
    tooManyRequests,
    requestHeaderFieldsTooLarge,
    unavailableForLegalReasons,
    internalServerError,
    notImplemented,
    badGateway,
    serviceUnavailable,
    gatewayTimeout,
    httpVersionNotSupported,
  }
}

declare class SKHTTPResponder extends JSObject{
  static initWithRequest<T>(this: { new(): T }, request: SKHTTPRequest, context: SKHTTPResponderContext | null): T;
  initWithRequest(request: SKHTTPRequest, context: SKHTTPResponderContext | null): this | void
  request: SKHTTPRequest;
  context: SKHTTPResponderContext | null;
  contextClass: JSClass | null;
  addAllowedOrigin(origin: string): void;
  addAllowedOrigin(origin: string, methods: string[]): void;
  addAllowedOrigin(origin: string, methods: string[], headers: string[]): void;
  allowedOrigins: {};
  authenticate(): Promise<SKHTTPAuthorization>;
  sendData(data: JSData, contentType: JSMediaType, status?: JSURLResponse.StatusCode): void;
  sendString(string: string, contentType: JSMediaType, status?: JSURLResponse.StatusCode): void;
  sendObject(object: object, status?: JSURLResponse.StatusCode): void;
  sendStatus(status: SKHTTPResponse.StatusCode): void;
  sendRedirect(destination: JSURL): void;
  sendResourceNamed(name: string, ext: string, bundle?: JSBundle, statusCode?: SKHTTPResponse.StatusCode): void;
  sendResource(metadata: JSBundle.Metadata, statusCode?: SKHTTPResponse.StatusCode): void;
  sendFile(filePath: string, contentType: string, hash: string, statusCode?: SKHTTPResponse.StatusCode): void;
  fail(error: Error): Promise<void> | null;
  urlForResponder(responder: JSClass, params: {}): JSURL;
  options(): Promise<void>;
  objectMethodForRequestMethod(requestMethod: string): (() => void);
  objectMethodForUpgrade(upgrade: string): (() => void);
}
declare namespace SKHTTPResponder{
  type AllowedOrigin = {
    methods?: string[] | null;
    headers?: string[] | null;
  };
}

declare class SKHTTPAuthorization{
  constructor(authorized: boolean, authenticated?: any | null);
  constructor(authorized: boolean, authenticated: any | null, statusCode: SKHTTPResponse.StatusCode);
  authorized: boolean;
  authenticated: any | null;
  statusCode: SKHTTPResponse.StatusCode;
}
declare function SKHTTPAuthorization(authorized: boolean, authenticated?: any | null): SKHTTPAuthorization;
declare function SKHTTPAuthorization(authorized: boolean, authenticated: any | null, statusCode: SKHTTPResponse.StatusCode): SKHTTPAuthorization;


declare class SKHTTPResponderContext extends JSObject{
  static initWithPathComponentMatches<T>(this: { new(): T }, pathComponentMatches: {}): T;
  initWithPathComponentMatches(pathComponentMatches: {}): this | void
  authenticated: any | null;
  open(): Promise<void>;
  assert(condition: boolean, statusCode: SKHTTPResponse.StatusCode, message: string): void;
  assertEquals(a: any, b: any, statusCode: SKHTTPResponse.StatusCode, message: string): void;
  assertEquals(value: any, statusCode: SKHTTPResponse.StatusCode, message: string): void;
}

declare enum SKHTTPHeaders{
  contentType,
  contentLength,
  etag,
  lastModified,
}

declare class SKUserAgent extends JSObject{
  static initWithString<T>(this: { new(): T }, string: string | null): T | null;
  initWithString(string: string | null): this | void | null
  products: SKUserAgent.Product[];
  containsProduct(name: string): boolean;
  containsProduct(name: string, version: string): boolean;
  versionOfProduct(name: string): string | null;
  comments: string[];
  containsComment(comment: string): boolean;
}
declare namespace SKUserAgent{
  type Product = {
    name: string;
    version: string | null;
  };
}

declare class SKHTTPError{
  constructor(statusCode: SKHTTPResponse.StatusCode, message: string);
  constructor(statusCode: SKHTTPResponse.StatusCode, message: string, object: {});
  statusCode: SKHTTPResponse.StatusCode;
  message: string;
  object: {} | null;
}
declare function SKHTTPError(statusCode: SKHTTPResponse.StatusCode, message: string): SKHTTPError;
declare function SKHTTPError(statusCode: SKHTTPResponse.StatusCode, message: string, object: {}): SKHTTPError;


declare class SKHTTPWebSocket extends JSObject{
  delegate: SKHTTPWebSocketDelegate | null;
  sendMessage(data: JSData): void;
  startMessage(data: JSData): void;
  continueMessage(data: JSData, isFinal: boolean): void;
  pingInterval: number;
  sendPing(): void;
}
declare namespace SKHTTPWebSocket{
  enum Status{
    normal,
    goingAway,
    protocolError,
    unsupportedDataType,
    invalidData,
    generic,
    messageTooLarge,
  }
}

declare interface SKHTTPWebSocketDelegate{
  socketDidReceiveMessage?(socket: SKHTTPWebSocket, chunks: JSData[]): void;
  socketDidReceiveData?(socket: SKHTTPWebSocket, data: JSData): void;
  socketDidClose?(socket: SKHTTPWebSocket): void;
}

declare class SKHTTPWebSocketResponder extends SKHTTPResponder implements SKHTTPWebSocketDelegate{
  supportedProtocols: string[];
  protocol: string | null;
  sendMessage(message: JSData): void;
  startMessage(chunk: JSData): void;
  continueMessage(chunk: JSData, isFinal: boolean): void;
  websocketEstablished(socket: SKHTTPWebSocket): void;
  socketDidReceiveMessage(socket: SKHTTPWebSocket, chunks: JSData[]): void;
  socketDidClose(socket: SKHTTPWebSocket): void;
  websocket(): void;
  socketDidReceiveData?(socket: SKHTTPWebSocket, data: JSData): void;
}

declare class SKValidatingObject extends JSObject{
  static initWithObject<T>(this: { new(): T }, object: {}): T;
  initWithObject(object: {}): this | void
  static initWithForm<T>(this: { new(): T }, form: JSFormFieldMap): T;
  initWithForm(form: JSFormFieldMap): this | void
  stringForKey(key: string): string;
  stringForKey(key: string, validator: (string: string) => void): string;
  stringForKey(key: string, defaultValue: string | null): string;
  stringForKey(key: string, defaultValue: string | null, validator: (string: string) => void): string;
  stringForKeyInLengthRange(key: string, min: number, max: number): string;
  stringForKeyInLengthRange(key: string, min: number, max: number, defaultValue: string | null): string;
  emailForKey(key: string): string;
  emailForKey(key: string, defaultValue: string | null): string;
  phoneForKey(key: string): string;
  phoneForKey(key: string, defaultValue: string | null): string;
  urlForKey(key: string): JSURL;
  urlForKey(key: string, defaultValue: string | null): string;
  numberForKey(key: string): number;
  numberForKey(key: string, validator: (number: number) => void): number;
  numberForKey(key: string, defaultValue: number | null): number;
  numberForKey(key: string, defaultValue: number | null, validator: (number: number) => void): number;
  numberForKeyInRange(key: string, min: number, max: number): number;
  numberForKeyInRange(key: string, min: number, max: number, defaultValue: number | null): number;
  integerForKey(key: string): number;
  integerForKey(key: string, defaultValue: number | null): number;
  integerForKeyInRange(key: string, min: number, max: number): number;
  integerForKeyInRange(key: string, min: number, max: number, defaultValue: number | null): number;
  booleanForKey(key: string): boolean;
  booleanForKey(key: string, defaultValue: boolean): boolean;
  objectForKey(key: string): SKValidatingObject;
  objectForKey(key: string, defaultValue: object): SKValidatingObject;
  validObjectForKey(key: string, validatingConstructionClass: JSClass): SKValidatingConstruction;
  validObjectForKey(key: string, validatingConstructionClass: JSClass, defaultValue: object): SKValidatingConstruction;
  arrayForKey(key: string): SKValidatingObject;
  arrayForKey(key: string, defaultValue: any[]): SKValidatingObject;
  optionForKey(key: string, optionSet: Set<any>): any;
  optionForKey(key: string, optionSet: Set<any>, defaultValue: any): any;
  base64DataForKey(key: string): JSData;
  base64DataForKey(key: string, defaultValue: boolean): JSData;
  base64URLDataForKey(key: string): JSData;
  base64URLDataForKey(key: string, defaultValue: boolean): JSData;
  getKeys(): string[];
  length: number;
}
declare namespace SKValidatingObject{
  type ErrorInfo = {
    field: string;
    problem: string;
    expected: string | null;
    format: string | null;
    min: number | null;
    max: number | null;
    provided: number | null;
  };
  class Error{
    constructor(info: SKValidatingObject.ErrorInfo, message?: string);
    info: SKValidatingObject.ErrorInfo;
    message: string;
  }
  function Error(info: SKValidatingObject.ErrorInfo, message?: string): Error;
  
}

declare interface SKValidatingConstruction{
  initWithValidatingObject(validatingObject: SKValidatingObject): this | void
}

declare class SKSecrets extends JSObject{
  static initWithNames<T>(this: { new(): T }, names: string[]): T;
  initWithNames(names: string[]): this | void
  valueForName(name: string): string | null;
  stringForName(name: string): string | null;
  urlForName(name: string): JSURL | null;
  urlForName(name: string, baseURL: JSURL): JSURL | null;
  integerForName(name: string): number | null;
  base64DataForName(name: string): JSData | null;
  base64URLDataForName(name: string): JSData | null;
  hex4DataForName(name: string): JSData | null;
  addProvider(provider: SKSecretsProvider): void;
}

declare class SKSecretsProvider extends JSObject{
  secretForName(name: string): string | null;
}

declare class SKSecretsEnvironmentProvider extends JSObject{
  secretForName(name: string): string | null;
}
