// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./ServerKit" />

declare class SKMockURLSession extends JSURLSession{
  server: SKMockHTTPServer;
}

declare class SKMockHTTPServer extends SKHTTPServer{
}
