// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />

declare class TKTestSuite extends JSObject{
  setup(): void;
  teardown(): void;
  wait(expectation: TKExpectation, timeout: number): void;
  getResourceData(resourceName: string, ext: string, completion: (data: JSData) => void, target?: object): void;
  now(): number;
  requiredEnvironment: string;
}

declare class TKExpectation extends JSObject{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  call(method: (() => void), target: object, ...args: any[]): void;
}

declare function TKAssert(condition: boolean, message?: string): void;

declare function TKAssertEquals(result: any, expected: any, message?: string): void;

declare function TKAssertNotEquals(result: any, expected: any, message?: string): void;

declare function TKAssertFloatEquals(result: any, expected: any, threshold?: number, message?: string): void;

declare function TKAssertExactEquals(result: any, expected: any, message?: string): void;

declare function TKAssertNotExactEquals(result: any, expected: any, message?: string): void;

declare function TKAssertObjectEquals(result: any, expected: any, message?: string): void;

declare function TKAssertObjectNotEquals(result: any, expected: any, message?: string): void;

declare function TKAssertNotNull(value: any, message?: string): void;

declare function TKAssertNull(value: any, message?: string): void;

declare function TKAssertNotUndefined(value: any, message?: string): void;

declare function TKAssertUndefined(value: any, message?: string): void;

declare function TKAssertThrows(fn: (() => void), message?: string): void;

declare function TKAssertLessThan(result: any, expected: any, message?: string): void;

declare function TKAssertLessThanOrEquals(result: any, expected: any, message?: string): void;

declare function TKAssertGreaterThan(result: any, expected: any, message?: string): void;

declare function TKAssertGreaterThanOrEquals(result: any, expected: any, message?: string): void;

declare function TKAssertArrayEquals(result: any, expected: any, message?: string): void;

declare function TKAssertType(obj: any, expectedType: string, message?: string): void;

declare function TKAssertInstance(obj: any, expectedType: any, message?: string): void;

declare function TKAssertPromiseRejected(promise: Promise<void>, message?: string): Promise<void>;
