// Auto-generated by `jskit doc --typescript`
// To make updates, edit documentation and regenerate

/// <reference types="./Foundation" />
/// <reference types="./UIKit" />

declare class UIMockApplication extends UIApplication{
  static init<T>(this: { new(): T }): T;
  init(): this | void
  run(): void;
  stop(): void;
  updateDisplay(): void;
  updateDisplay(intervalFromPreviousUpdate: JSTimeInterval): void;
}
