// Copyright 2022 Breakside Inc.
//
// Licensed under the Breakside Public License, Version 1.0 (the "License");
// you may not use this file except in compliance with the License.
// If a copy of the License was not distributed with this file, you may
// obtain a copy at
//
//     http://breakside.io/licenses/LICENSE-1.0.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// #import UIKit
// #import TestKit
// #import UIKitTesting
"use strict";

JSClass("UISplitViewControllerTests", TKTestSuite, {

    app: null,
    window: null,
    device: null,

    setup: function(){
        this.device = UIDevice.shared;
        this.app = UIMockApplication.initEmpty();
        var expectation = TKExpectation.init();
        expectation.call(this.app.run, this.app, function(error){
            TKAssertNull(error);
            this.window = UIRootWindow.initWithApplication(this.app);
            this.window.makeKeyAndOrderFront();
            this.app.updateDisplay();
        }, this);
        this.wait(expectation, 1.0);
    },

    teardown: function(){
        UIDevice.shared = this.device;
        var expectation = TKExpectation.init();
        expectation.call(this.app.stop, this.app, function(){
            this.app = null;
        }, this);
        this.wait(expectation, 1.0);
    },

    testInit: function(){
        var splitViewController = UISplitViewController.init();
        TKAssertNull(splitViewController.leadingViewController);
        TKAssertNull(splitViewController.mainViewController);
        TKAssertNull(splitViewController.trailingViewController);
    },

    testInitWithSpec: function(){
        var spec = JSSpec.initWithDictionary({
            leadingViewController: {class: "UINavigationController", root: {class: "UIViewController"}},
            mainViewController: {class: "UIViewController"},
        });
        var splitViewController = UISplitViewController.initWithSpec(spec);
        TKAssertExactEquals(splitViewController.isViewLoaded, false);
        TKAssertInstance(splitViewController.leadingViewController, UINavigationController);
        TKAssertInstance(splitViewController.mainViewController, UIViewController);
        TKAssertNull(splitViewController.trailingViewController);
    },

    testLoadView: function(){
        var splitViewController = UISplitViewController.init();
        splitViewController.leadingViewController = UIViewController.init();
        splitViewController.mainViewController = UIViewController.init();
        splitViewController.trailingViewController = UIViewController.init();
        var view = splitViewController.view;
        TKAssertInstance(view, UISplitView);
        TKAssertExactEquals(splitViewController.isViewLoaded, true);
        TKAssertExactEquals(splitViewController.leadingViewController.isViewLoaded, true);
        TKAssertExactEquals(splitViewController.mainViewController.isViewLoaded, true);
        TKAssertExactEquals(splitViewController.trailingViewController.isViewLoaded, true);
        TKAssertExactEquals(splitViewController.leadingViewController.view.superview, splitViewController.view);
        TKAssertExactEquals(splitViewController.mainViewController.view.superview, splitViewController.view);
        TKAssertExactEquals(splitViewController.trailingViewController.view.superview, splitViewController.view);
    },

    testViewLifecycle: function(){
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        var trailingViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = leadingViewController;
        splitViewController.mainViewController = mainViewController;
        splitViewController.trailingViewController = trailingViewController;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 0);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 0);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 0);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 0);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.window.contentViewController = splitViewController;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 0);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 0);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.window.contentViewController = UIViewController.init();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);

        splitViewController.leadingViewController = null;
        splitViewController.mainViewController = null;
        splitViewController.trailingViewController = null;
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.window.contentViewController = null;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);

        splitViewController.leadingViewController = leadingViewController;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);

        splitViewController.mainViewController = mainViewController;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);

        splitViewController.trailingViewController = trailingViewController;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.leadingViewController = null;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.mainViewController = null;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 2);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 2);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 2);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.trailingViewController = null;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 2);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 2);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 2);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 2);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 2);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, false);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
    },

    testToggleViews: function(){
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        var trailingViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = leadingViewController;
        splitViewController.mainViewController = mainViewController;
        splitViewController.trailingViewController = trailingViewController;
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.hideLeadingView(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.showLeadingView(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);

        splitViewController.hideTrailingView(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 1);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);

        splitViewController.showTrailingView(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 1);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertEquals(trailingViewController.viewWillAppearCount, 2);
        TKAssertEquals(trailingViewController.viewDidAppearCount, 2);
        TKAssertEquals(trailingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(trailingViewController.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(trailingViewController.isViewVisible, true);
    },

    testSetMainViewController: function(){
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController1 = UISplitViewControllerTestsViewController.init();
        var mainViewController2 = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        splitViewController.mainViewController = mainViewController1;
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);

        splitViewController.mainViewController = mainViewController2;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, true);
    },

    testSetMainViewControllerCollapsed: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        this.app.setScreenSize(JSSize(400, 600));
        this.app.updateDisplay();
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController1 = UISplitViewControllerTestsViewController.init();
        var mainViewController2 = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);

        splitViewController.mainViewController = mainViewController1;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController1);
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);

        splitViewController.mainViewController = mainViewController2;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController2);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, true);

        splitViewController.leadingViewController.popViewController(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);

        splitViewController.mainViewController = mainViewController1;
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController1);
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
    },

    testSetMainNavigationControllerCollapsed: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        this.app.setScreenSize(JSSize(400, 600));
        this.app.updateDisplay();
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController1 = UISplitViewControllerTestsViewController.init();
        var mainViewController2 = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);

        splitViewController.mainViewController = UINavigationController.initWithRootViewController(mainViewController1);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController1);
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 0);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);

        splitViewController.mainViewController = UINavigationController.initWithRootViewController(mainViewController2);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 0);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController2);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, true);

        splitViewController.leadingViewController.popViewController(false);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);

        splitViewController.mainViewController = UINavigationController.initWithRootViewController(mainViewController1);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController1.isViewVisible, false);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController1);
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 2);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 2);
        TKAssertEquals(mainViewController1.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController1.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController1.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController1.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController2.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController2.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController2.viewDidDisappearCount, 1);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController1.isViewVisible, true);
        TKAssertExactEquals(mainViewController2.isViewVisible, false);
    },

    testCollapseMainView: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        splitViewController.mainViewController = mainViewController;
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);

        this.app.setScreenSize(JSSize(400, 600));
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
    },

    testCollapseMainNavigation: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        splitViewController.mainViewController = UINavigationController.initWithRootViewController(mainViewController);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 0);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);

        this.app.setScreenSize(JSSize(400, 600));
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 0);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
    },

    testUncollapseMainView: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        this.app.setScreenSize(JSSize(400, 600));
        this.app.updateDisplay();
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        splitViewController.mainViewController = mainViewController;
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController);

        this.app.setScreenSize(JSSize(1500, 1200));
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
    },

    testUncollapseMainNavigation: function(){
        UIDevice.shared = UIDevice.init();
        UIDevice.shared.primaryPointerType = UIUserInterface.PointerType.touch;
        this.app.setScreenSize(JSSize(400, 600));
        this.app.updateDisplay();
        var splitViewController = UISplitViewController.init();
        var leadingViewController = UISplitViewControllerTestsViewController.init();
        var mainViewController = UISplitViewControllerTestsViewController.init();
        splitViewController.leadingViewController = UINavigationController.initWithRootViewController(leadingViewController);
        this.window.contentViewController = splitViewController;
        this.app.updateDisplay();
        splitViewController.mainViewController = UINavigationController.initWithRootViewController(mainViewController);
        this.app.updateDisplay();
        this.app.updateDisplay(UIAnimation.Duration.transition);
        TKAssertEquals(leadingViewController.viewWillAppearCount, 1);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 1);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 0);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 2);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[1], mainViewController);

        this.app.setScreenSize(JSSize(1500, 1200));
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 1);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 1);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, false);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers.length, 1);
        TKAssertExactEquals(splitViewController.leadingViewController.viewControllers[0], leadingViewController);
        this.app.updateDisplay();
        TKAssertEquals(leadingViewController.viewWillAppearCount, 2);
        TKAssertEquals(leadingViewController.viewDidAppearCount, 2);
        TKAssertEquals(leadingViewController.viewWillDisappearCount, 1);
        TKAssertEquals(leadingViewController.viewDidDisappearCount, 1);
        TKAssertEquals(mainViewController.viewWillAppearCount, 2);
        TKAssertEquals(mainViewController.viewDidAppearCount, 2);
        TKAssertEquals(mainViewController.viewWillDisappearCount, 1);
        TKAssertEquals(mainViewController.viewDidDisappearCount, 0);
        TKAssertExactEquals(leadingViewController.isViewVisible, true);
        TKAssertExactEquals(mainViewController.isViewVisible, true);
    },

});

JSClass("UISplitViewControllerTestsViewController", UIViewController, {

    viewWillAppearCount: 0,
    viewDidAppearCount: 0,
    viewWillDisappearCount: 0,
    viewDidDisappearCount: 0,

    viewWillAppear: function(animated){
        UISplitViewControllerTestsViewController.$super.viewWillAppear.call(this, animated);
        ++this.viewWillAppearCount;
    },

    viewDidAppear: function(animated){
        UISplitViewControllerTestsViewController.$super.viewDidAppear.call(this, animated);
        ++this.viewDidAppearCount;
    },

    viewWillDisappear: function(animated){
        UISplitViewControllerTestsViewController.$super.viewWillDisappear.call(this, animated);
        ++this.viewWillDisappearCount;
    },

    viewDidDisappear: function(animated){
        UISplitViewControllerTestsViewController.$super.viewDidDisappear.call(this, animated);
        ++this.viewDidDisappearCount;
    }

});