// Copyright 2020 Breakside Inc.
//
// Licensed under the Breakside Public License, Version 1.0 (the "License");
// you may not use this file except in compliance with the License.
// If a copy of the License was not distributed with this file, you may
// obtain a copy at
//
//     http://breakside.io/licenses/LICENSE-1.0.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// #import jskit
// #import TestKit
'use strict';

JSClass("ConstraintsTests", TKTestSuite, {

    testConstraintsFromEquality: function(){
        var refs = {
            one: "/One",
            two: "/Two",
            n: 10
        };
        var constraint = constraintFromEquality("this.width = 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertUndefined(constraint.firstItem);
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("one.width = 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, "/One");
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("two.width = 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, "/Two");
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("three.width = 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, "three");
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("this.height = n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'height');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("one.top = this.top", refs);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        constraint = constraintFromEquality("one.top = this.top + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        constraint = constraintFromEquality("one.top = this.top + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        constraint = constraintFromEquality("one.top = this.top - 12", refs);
        TKAssertEquals(constraint.constant, -12);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        constraint = constraintFromEquality("one.top = this.top - n", refs);
        TKAssertEquals(constraint.constant, -10);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        constraint = constraintFromEquality("two.width = one.width * 2", refs);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2.5", refs);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2 + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2.5 + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2 + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2.5 + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2 - 12", refs);
        TKAssertEquals(constraint.constant, -12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2.5 - 12", refs);
        TKAssertEquals(constraint.constant, -12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2 - n", refs);
        TKAssertEquals(constraint.constant, -10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("two.width = one.width * 2.5 - n", refs);
        TKAssertEquals(constraint.constant, -10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("this.width = 12 @ 100", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.priority, 100);
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("this.width = 12 @ defaultLow", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.priority, 'defaultLow');
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("this.width = one.width * 2 + 3 @ 100", refs);
        TKAssertEquals(constraint.constant, 3);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.priority, 100);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        constraint = constraintFromEquality("this.width = one.width * 2 + 3 @ defaultLow", refs);
        TKAssertEquals(constraint.constant, 3);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.priority, 'defaultLow');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');


        constraint = constraintFromEquality("this.margins.width = 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("this.margins.height = n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'height');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.relation, 'equal');
        constraint = constraintFromEquality("one.margins.top = this.top", refs);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertUndefined(constraint.secondProperty);
        constraint = constraintFromEquality("one.top = this.margins.top", refs);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertUndefined(constraint.firstProperty);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("one.margins.top = this.margins.top", refs);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("one.margins.top = this.margins.top + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("one.margins.top = this.margins.top + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("one.margins.top = this.margins.top - 12", refs);
        TKAssertEquals(constraint.constant, -12);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("one.margins.top = this.margins.top - n", refs);
        TKAssertEquals(constraint.constant, -10);
        TKAssertEquals(constraint.firstAttribute, 'top');
        TKAssertEquals(constraint.firstItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'top');
        TKAssertEquals(constraint.secondItemName, 'this');
        TKAssertEquals(constraint.secondProperty, 'margins');
        constraint = constraintFromEquality("two.margins.width = one.width * 2", refs);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertUndefined(constraint.secondProperty);
        constraint = constraintFromEquality("two.width = one.margins.width * 2.5", refs);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.secondProperty, 'margins');
        TKAssertUndefined(constraint.firstProperty);
        constraint = constraintFromEquality("two.margins.width = one.width * 2 + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertUndefined(constraint.secondProperty);
        constraint = constraintFromEquality("two.width = one.margins.width * 2.5 + 12", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.secondProperty, 'margins');
        TKAssertUndefined(constraint.firstProperty);
        constraint = constraintFromEquality("two.margins.width = one.width * 2 + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.firstProperty, 'margins');
        TKAssertUndefined(constraint.secondProperty);
        constraint = constraintFromEquality("two.width = one.margins.width * 2.5 + n", refs);
        TKAssertEquals(constraint.constant, 10);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItem, '/Two');
        TKAssertEquals(constraint.multiplier, 2.5);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.secondProperty, 'margins');
        TKAssertUndefined(constraint.firstProperty);
        constraint = constraintFromEquality("this.margins.width = 12 @ 100", refs);
        TKAssertEquals(constraint.constant, 12);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.priority, 100);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.firstProperty, 'margins');
        constraint = constraintFromEquality("this.width = one.margins.width * 2 + 3 @ 100", refs);
        TKAssertEquals(constraint.constant, 3);
        TKAssertEquals(constraint.firstAttribute, 'width');
        TKAssertEquals(constraint.firstItemName, 'this');
        TKAssertEquals(constraint.multiplier, 2);
        TKAssertEquals(constraint.priority, 100);
        TKAssertEquals(constraint.relation, 'equal');
        TKAssertEquals(constraint.secondAttribute, 'width');
        TKAssertEquals(constraint.secondItem, '/One');
        TKAssertEquals(constraint.secondProperty, 'margins');
        TKAssertUndefined(constraint.firstProperty);
    }

});